### ISSUE TITLE
How to access existing fonts

### ISSUE THREAD

**Issue by pammann-work** [Hopding/pdf-lib#110]
Can pdf-lib be used to access fonts already embedded in a template PDF?

**Comment by Hopding** [comment]
Hello @pammann-work!

I'm afraid this is a bit of a rabbit hole to go down. Trying to reuse fonts that have already been embedded into a PDF file is fraught with risks. 

One of the reasons it's so challenging is that fonts are often subsetted prior to being embedded. This means that the embedded version of the font is often not the complete font, but rather a portion of it that only describes how to draw the characters that were actually used in the PDF. Font subsetting can make the resulting PDF significantly smaller, but it makes font reuse challenging.

As such, I'd discourage you from going down this path if at all possible. And because of all the difficulties involved, it would take me a significant amount of time to come up with an example for you.

I hope this helps! Please let me know if you have any further questions.

**Comment by ElePhontitis** [comment]
@Hopding Is there a way to just get a list of the embedded Fonts? This way one could maybe load the full fonts dynamically. I have a pdf that I don't know the fonts in and the standard font used by pdf-lib totally destroys the layout.

**Comment by jeantil** [comment]
@DanielMenke you should be able to modify the following typescript snippet to get  what you want
```
function getFontRef(pdfDoc2: PDFDocument, fontName: string) {
  const [ref] = Array.from(pdfDoc2.index.index).find(([key, value]) => {
    if (value instanceof PDFDictionary) {
      const type = value.getMaybe('BaseFont');
      if (type && type instanceof PDFName && type.key === fontName) {
        return true;
      }
    } else {
      return false;
    }
  });
  return ref;
}
```
