### ISSUE TITLE
Please adapt for Content Security Policy: drop Function(string), if possible (eval)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Hopding/pdf-lib#13]
For example file
https://unpkg.com/pdf-lib/dist/pdf-lib.js
Line 30:
`var root = _freeGlobal || freeSelf || Function('return this')();`

Because of `Function('return this')` Chrome with CSP cannot execute this lib:
`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed`

More information about CSP here https://developer.chrome.com/extensions/contentSecurityPolicy

**Comment by Hopding** [comment]
I'm open to researching this issue. I think that particular line would have been inserted by [Rollup](https://rollupjs.org/guide/en) when building the `pdf-lib.js` and `pdf-lib.min.js` bundles, so it's probably not going to be fixed by a trivial change to `pdf-lib`'s source.

Can you please provide a minimum working example of the issue? An HTML file or zipped up collection of files should suffice.

**Comment by Hopding** [comment]
I believe I've found the cause of the issue. I've created a minimal example that reproduces it:

[rollup-test.zip](https://github.com/Hopding/pdf-lib/files/2195741/rollup-test.zip)

You can unzip this example and run `npm install && npm run-script build` to create the `bundle.js` file with `rollup`. You'll see that the bundle looks like the following:
```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory((global.Foo = {})));
}(this, (function (exports) { 'use strict';

	var commonjsGlobal = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

	/** Detect free variable `global` from Node.js. */
	var freeGlobal = typeof commonjsGlobal == 'object' && commonjsGlobal && commonjsGlobal.Object === Object && commonjsGlobal;

	var _freeGlobal = freeGlobal;

	/** Detect free variable `self`. */
	var freeSelf = typeof self == 'object' && self && self.Object === Object && self;

	/** Used as a reference to the global object. */
	var root = _freeGlobal || freeSelf || Function('return this')();
```
The cause of this seems to be importing a function directly from lodash, e.g. in the `foo.js` file of this example:
```javascript
// This type of import from lodash seems to be the cause:
import isString from 'lodash/isString';

export const foo = (x) => {
  console.log(isString(x));
};
```
I'm going to try some things to fix this. First on the list is replacing the plain `lodash` module with `lodash-es`.

**Comment by Hopding** [comment]
After further investigation, this problem is definitely caused by `lodash`: https://github.com/lodash/lodash/issues/3504. Here's the particular [file that's causing the issue](https://github.com/lodash/lodash/blob/f03b3edca4faecf07e45a5c495eb510ff73b78dc/.internal/root.js#L7):
```javascript
import freeGlobal from './freeGlobal.js'

/** Detect free variable `self`. */
const freeSelf = typeof self == 'object' && self !== null && self.Object === Object && self

/** Used as a reference to the global object. */
const root = freeGlobal || freeSelf || Function('return this')()

export default root
```
Simply using `lodash-es` instead of `lodash` does not solve the issue. I'll keep searching to find a solution.

**Comment by Hopding** [comment]
After taking a second look at the error thrown upon opening that HTML file you shared, I actually don't think `lodash` is the problem here. Lodash _does_ cause the `freeGlobal || freeSelf || Function('return this')()` line to be inserted, but that line isn't causing the error to be thrown, because the `Function('return this')()` expression is never being evaluated.

The error actually appears to arise from the [`bundle.js`](https://github.com/Hopding/fontkit/blob/master/bundle.js) file build of `pdf-lib`'s `fontkit` fork. So this issue is related to https://github.com/Hopding/pdf-lib/issues/14 as well.

**Comment by Hopding** [comment]
Version [`0.5.1`](https://www.npmjs.com/package/pdf-lib/v/0.5.1) is now published. It contains updated dependencies that no longer violate CSP. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.5.1).

You can install this new version with npm:
```
npm install pdf-lib@0.5.1
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.5.1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.5.1/dist/pdf-lib.min.js

-----

@vitaly-zdanevich This has been a long time coming. Sorry it took so long. It took me awhile to find the root causes. And actually fixing this issue involved forking and changing two dependencies:
  * https://github.com/Hopding/fontkit
  * https://github.com/Hopding/restructure

I just haven't had the time to investigate and make the necessary changes until now (on vacation for the holidays 😄). Anyhow, it should be fixed now. Thanks so much for reporting this issue!
