### ISSUE TITLE
Parsing text from PDF

### ISSUE THREAD

**Issue by nunofgs** [Hopding/pdf-lib#137]
Hi @Hopding, thank you for the great lib.

Apologies if this is a newbie question, but I can't seem to find a way to parse text out of an existing PDF. I'm looking to retrieve a string from a PDF in order to determine which page it's on.

Any idea how I could accomplish this?

**Comment by dasilvacontin** [comment]
I'm personally looking to find some text and replace the "field"'s contents

**Comment by Hopding** [comment]
Hello @nunofgs! 

It is not currently possible to parse plain text out of a document with pdf-lib (but you _can_ extract the content of acroform fields). I'd suggest you consider using [PDF.js](https://mozilla.github.io/pdf.js/) to parse/extract text. 

Of course, this isn't an ideal solution since it requires two different libraries for a seemingly simple task. But it's the best approach I know of for now, until pdf-lib gains support for text parsing.

**Comment by Hopding** [comment]
@dasilvacontin Is the field you are working with just plain text? Or is it an acroform field? If it is raw text, I'm afraid pdf-lib doesn't have the necessary features to parse it (but as I mentioned above, you could use [PDF.js](https://mozilla.github.io/pdf.js/) instead). 

However, if it's in an acroform, pdf-lib should be able to do what you need. pdf-lib's acroform support isn't currently well documented, so I'd suggest taking a look at some of the [existing acroform issues](https://github.com/Hopding/pdf-lib/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+acroform). Please let me know if you have any questions!

**Comment by CodeSmith32** [comment]
@Hopding, I'm a little familiar with the PDF specification, and I also know this library seems to expose the PDF document catalog (the data tree containing everything in the document). From my short use of the library, manipulating this tree via this API seems pretty intuitive.

Therefore, couple questions:
1. Doesn't this mean that, theoretically, given the time, anyone could use pdflib and write the parsing system themselves to do something like this?
2. Are all the high-level features of pdflib built this way? i.e., structured on top of the catalog tree API?
