### ISSUE TITLE
Missing PDFDictionary entry "Parent" (Copying PDF page with some annotations)

### ISSUE THREAD

**Issue by tema4p** [Hopding/pdf-lib#138]
Hi guys, I really appreciate your efforts in making our world better, at least with PDF part.
I worked a lot with your library (as well as with [PDFAssembler](https://www.npmjs.com/package/pdfassembler)) and will add some feedback soon.

But I've met some strange error when trying to copy from or add to pages to PDF files with some annotations. 
[test_text_annot.pdf](https://github.com/Hopding/pdf-lib/files/3411319/test_text_annot.pdf)

I use pdf-lib (0.6.3) in browser, investigated the issue and reviewed your code, but still can't figure out the problem, please help.

ERROR Error: Missing PDFDictionary entry "Parent".

I'll continue investigating and any support here would be great, thanks!

**Comment by Hopding** [comment]
Hello @tema4p! I'm glad you are finding pdf-lib useful. I look forward to your feedback.

I was able to reproduce this issue. It looks like the problem is caused by some page objects missing a required key (`/Parent`). The file you shared has a couple couple of pages with another missing key as well (`/Resources`), though this isn't the cause of the error. Technically, these missing keys make the file you shared invalid.

I'll work on a fix for this. I'll try to get it published within a couple of days. However, the the [beta release](https://github.com/Hopding/pdf-lib/issues/134) doesn't have this problem, and is able to copy the PDF without any errors. I'd recommend you try it out.

**Comment by Hopding** [comment]
I just released version `0.6.4`. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.4).

You can install it with `npm`:
```
npm install --save pdf-lib@0.6.4
```
or yarn:
```
yarn add pdf-lib@0.6.4
```
It's also available on the unpkg CDN:
* https://unpkg.com/pdf-lib@0.6.4/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.4/dist/pdf-lib.min.js

**Comment by Hopding** [comment]
@tema4p Please let me know if the fix works for you.

**Comment by tema4p** [comment]
@Hopding Thank you a lot!
That fixed my issue.
Sorry for the late response.
I'll try beta version and let you know! 
Thanks again!
