### ISSUE TITLE
High file size increase of PDF when editing with many pages

### ISSUE THREAD

**Issue by AldrinSalazar** [Hopding/pdf-lib#139]
First of all thanks to everyone collaborating in this awesome library. 🎉 

I am working on a tool that must me able to reorder an existing PDF in the browser without any server intervention, for that i am using Mozilla's PDF.js library to do the render part and this library to do the actual file edition. This is the code that i'm using to do such task:

```
/**
 *
 * @param {Uint8Array} file Raw PDF file bytes
 * @param {Array} newOrder array of the new page order, example: [3,1,2] means page 3 is now page 1 and so on
 */
const reorderPdf = (rawPdf, newOrder) => {
  const pdfDoc = PDFLib.PDFDocumentFactory.load(rawPdf);
  const pdfDocPages = pdfDoc.getPages();
  const outPdf = PDFLib.PDFDocumentFactory.create();
  
  for (let currentPage = 0; currentPage < newOrder.length; currentPage++) {
    outPdf.addPage(pdfDocPages[newOrder[currentPage] - 1]);
  }

  const outPdfBytes = PDFLib.PDFDocumentWriter.saveToBytes(outPdf, { useObjectStreams: true });
  bytes2File(outPdfBytes);
};
```
While testing with various files i notice that there is always a small increment in the size, this was without any reordering being done. After all of the testing i concluded that when creating a PDF there is a significant overhead in size attached to the creation of a page, take for example this table (will provide files at the end):

|  File Name | Original Size | Pages | New Size | Increment |
|:----------:|:-------------:|:-----:|:--------:|:---------:|
| document A |     75.8 KB    |   4   |   87 KB   |   +14%~   |
| document B |     224 KB     |   38  |  1,841 KB  |   +800%~  |
| document C |     2,238 KB    |   7   |  3,331 KB  |   +48%~   |
| document D |     1,898 KB    |  229  |  44,354 KB |  +2200%~  |

- Document A, which has a small size only gets increased a bit after passing it to my function.
- Document B which has a considerable number of pages get increased **a lot** with respect to the original size, still not a problem since the resultant size is manageable.
- Document C and D is where things get wild, notice how they both are about the same size (2 MB), but with much larger page difference. The result of document B is noticeable big but still, manageable, but the result of document D is really a problem, with an increment of 2200%. 

The behaviour of those last 2 documents gets worse the more pages the original document has, with a case of **a document of 500 pages with only 7MB in sice increasing up to 150MB.**

Thanks for your time.

---
Files:
[document A.pdf](https://github.com/Hopding/pdf-lib/files/3413109/document.A.pdf)
[document B.pdf](https://github.com/Hopding/pdf-lib/files/3413110/document.B.pdf)
[document C.pdf](https://github.com/Hopding/pdf-lib/files/3413111/document.C.pdf)
[document D.pdf](https://github.com/Hopding/pdf-lib/files/3413112/document.D.pdf)

**Comment by Hopding** [comment]
Hello @AldrinSalazar!

You've stumbled upon a flaw in the design of pdf-lib's page copying API. The version of this API that exists in `v0.x.x` will often create duplicate objects whenever more than one page is copied between different `PDFDocument` objects.

This flaw will be fixed in `v1.0.0`. This version is currently in beta ([`1.0.0-beta.3`](https://www.npmjs.com/package/pdf-lib/v/1.0.0-beta.3)). I'd recommend you try it out. I'm hoping to do a full release of v1.0.0 within 2-3 weeks. Most of the remaining work is just documenting things.

That being said, there is a better way to implement page reordering. This approach is faster and also avoids creating duplicate objects. Basically, instead of creating two `PDFDocument` objects and copying pages between them, you can create a single `PDFDocument` and reorder pages within it. Here are some examples to clarify things:

### Bad Page Reversal

This implementation is slower than necessary, and also ends up bloating the resulting file. It's slow due to the nature of the implementation (and it would also be slow in `v1.0.0`). It bloats the file size due to an API flaw in `v0.x.x`:

```js
const badReversePages = rawPdf => {
  const pdfDoc = PDFDocumentFactory.load(rawPdf);
  const newDoc = PDFDocumentFactory.create();
  pdfDoc
    .getPages()
    .reverse()
    .forEach(page => {
      newDoc.addPage(page);
    });
  return PDFDocumentWriter.saveToBytes(newDoc);
};

const fs = require('fs');
const rawPdf = fs.readFileSync('document D.pdf');

console.time('badReversePages');
const pdfBytes = badReversePages(rawPdf);
console.timeEnd('badReversePages');
console.log('pdfBytes.length ===', pdfBytes.length);

// => badReversePages: 878.281ms
// => pdfBytes.length === 45418620
```

### Good Page Reversal

This implementation is much faster (~57%) and avoids bloating the file:

```js
const goodReversePages = (rawPdf: any) => {
  const pdfDoc = PDFDocumentFactory.load(rawPdf);
  const pages = pdfDoc.getPages();
  pdfDoc
    .getPages()
    .reverse()
    .forEach((page, idx) => {
      pdfDoc.removePage(idx);
      pdfDoc.insertPage(idx, page);
    });
  return PDFDocumentWriter.saveToBytes(pdfDoc);
};

const fs = require('fs');
const rawPdf = fs.readFileSync('document D.pdf');

console.time('goodReversePages');
const pdfBytes = goodReversePages(rawPdf);
console.timeEnd('goodReversePages');
console.log('pdfBytes.length ===', pdfBytes.length);

// => goodReversePages: 372.451ms
// => pdfBytes.length === 1883468
```

### Comparison

The original size of the input document (`document D.pdf`) is `1943532` bytes (1.94 MB).

| Implementation | Speed | Output Size | Difference |
| -------------- | ----- | ----------- | ---------- |
| Bad            | 878ms | ~45 MB      | +43 MB     |
| Good           | 372ms | 1.88 MB     | -0.06 MB   |

As you can see, the good implementation is actually able to _decrease_ the size of the document (despite not having removed any pages).

### Reimplemented `reorderPdf`

Here's a verion of the `reorderPdf` function with the "good" implementation:

```js
/**
 *
 * @param {Uint8Array} file Raw PDF file bytes
 * @param {Array} newOrder array of the new page order, example: [3,1,2] means page 3 is now page 1 and so on
 */
const reorderPdf = (rawPdf, newOrder) => {
  const pdfDoc = PDFDocumentFactory.load(rawPdf);

  const pages = pdfDoc.getPages();
  for (let currentPage = 0; currentPage < newOrder.length; currentPage++) {
    pdfDoc.removePage(currentPage);
    pdfDoc.insertPage(currentPage, pages[newOrder[currentPage] - 1]);
  }

  const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
  return bytes2File(pdfBytes);
};
```

I hope this helps! Please let me know if you have any additional questions.

**Comment by AldrinSalazar** [comment]
Thanks for your very detailed answer! it helped a lot and indeed it makes PDF a little smaller and is faster. I dont know if this is a common use case but i think it would be a good idea to have that snippet of code as one of the examples in the lib.

Thanks!

**Comment by shreevatsa** [comment]
Sorry for resurrecting a months-old closed thread but I wanted to say thanks for this thread and for the detailed comment above; this specific page came up when I was searching for how to do this and I'm glad to have learned of this project/library... it helped me scratch a minor itch and write a trivial (given `pdf-lib`) [tool](https://shreevatsa.net/mobius-print/). :-)

**Comment by Hopding** [comment]
@shreevatsa That's a really neat tool you've built! Thanks for sharing. I really enjoy seeing the cool things people use `pdf-lib` for.
