### ISSUE TITLE
pdf-lib.min.js filesize is 1.1 MB, maybe is it possible to introduce a custom builds?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Hopding/pdf-lib#14]
Not all users need all options, maybe from this library the most of us only need the ability of adding the texts.

Builder example http://fabricjs.com/build/:
![image](https://user-images.githubusercontent.com/3514015/42410752-cfbf67d2-81f7-11e8-8ab7-bbb8a43b864d.png)

1.1 MB is very big.

**Comment by Hopding** [comment]
Yes, 1.1 MB is big for sure. The primary cause of this is the `fontkit` fork dependency. It's [`bundle.js`](https://github.com/Hopding/fontkit/blob/master/bundle.js) file is 895 KB. Reducing `pdf-lib`'s bundle size is currently an item on the [todo list](https://github.com/Hopding/pdf-lib/blob/master/TODO.md#dependencies).

I think the size of the fontkit `bundle.js` file could be reduced by optimizing the build process used for it. But I'm not sure to what extent. The official (non-forked) [build of fontkit](https://unpkg.com/fontkit@1.7.7/index.js) is still 519 KB. After minifying it with https://jscompress.com/, its size drops to 240 KB. This build doesn't work in all JS environments either, so it's unlikely that the forked build can become quite this small. But there's currently a 660 KB difference between the two. I'm reasonably sure that difference could be made significantly smaller.

Let's say the size of the forked build of fontkit could be reduced to 350 KB (total guess). The size of `pdf-lib.min.js` would then be 555 KB. So that's about a 50% reduction in its current size.

It may be, as you suggest, possible to build custom bundles that omit certain features of the library. In particular, it would be possible to create a build of `pdf-lib` that doesn't support embedding custom fonts (you would be restricted to using one of the [Standard 14 Fonts](https://github.com/Hopding/pdf-lib/blob/master/docs/modules/_core_pdf_document_standard14fonts_.md)). This build would not include the fontkit dependency at all, so it's bundle size would be about 205 KB. That's a size reduction of 81.4%.

I'm curious, are you intending to use the font embedding feature of `pdf-lib`?

**Comment by vitaly-zdanevich** [comment]
Now I use `embedStandardFont('Helvetica')` according to the documentation.

**Comment by Hopding** [comment]
I've been exploring some different ways to reduce the bundle size this weekend. I've been able to reduce the bundle's size by around 200KB. This is certainly _better_, but still not great. Most of the size of the bundle is still due to the `fontkit` dependency.

I think I'll wind up publishing two UMD module builds. One will have the `fontkit` dependency bundled within it, and the other will not. The size of the build without `fontkit` will be reduced substantially. Again, this would mean users of that build couldn't embed fonts, but at least the option would exist.

**Comment by Hopding** [comment]
Version [`0.5.1`](https://www.npmjs.com/package/pdf-lib/v/0.5.1) is now published. It contains updated dependencies that reduce pdf-lib's minified bundle size by 21% (236 KB). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.5.1).

You can install this new version with npm:
```
npm install pdf-lib@0.5.1
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.5.1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.5.1/dist/pdf-lib.min.js

-----

@vitaly-zdanevich This has been a long time coming. Sorry it took so long. Getting this reduction in bundle size was quite arduous. As I mentioned before, the primary cause of pdf-lib's large bundle size is the `fontkit` dependency. I was able to compress the size of that dependency by forking it (and two transitive dependencies) and making some changes to the source, as well as the release steps/configurations:

* https://github.com/Hopding/fontkit
* https://github.com/Hopding/unicode-properties
* https://github.com/Hopding/brotli.js

I'm not planning on implementing custom builds in the near term. This would require too much effort to setup and maintain that I think would be more valuable doing other work on the library. Of course, if anybody wants to step up and work on implementing custom builds (or a larger variety of static builds), I'd be happy to help out.

Another option might be to serve gzipped versions of the bundle. The gzipped version of the minified bundle is just 371 KB in size. That's 57% smaller than the non-gzipped version. This probably wouldn't be too hard to setup. I'll probably explore this possibility over the next few days.

-----

Also, here is a visualization of the bundle: [bundle_stats.html.txt](https://github.com/Hopding/pdf-lib/files/2699756/bundle_stats.html.txt) (produced with https://github.com/btd/rollup-plugin-visualizer). You can open this file in a browser to interactively explore the different components of the bundle, and what percentage of the bundle they make up. Here's a quick summary:

* `pdf-lib` source code: 15%
* `lodash` dependency: 7.5%
* `pako` dependency: 13%
* `fontkit` dependency: 64%
