### ISSUE TITLE
size of page (ex. A4)

### ISSUE THREAD

**Issue by Paul75** [Hopding/pdf-lib#143]
Hello,

in create page what is the correct config to have page A4 ?  210 x 297 mm ?

Thanks

**Comment by Hopding** [comment]
Hello @Paul75!

Version v1.0.0 will have a [`PageSizes`](https://github.com/Hopding/pdf-lib/blob/Rewrite/src/api/sizes.ts#L1) object that contains a lot of standard page dimensions. So in that version, you'll be able to use `PageSizes.A4`. But since this object does not exist in v0.6.4, you can use [these dimensions: `[595.28, 841.89]`](https://github.com/Hopding/pdf-lib/blob/Rewrite/src/api/sizes.ts#L8).

I hope this helps. Let me know if you have any additional questions!

**Comment by Paul75** [comment]
but the last version is the 0.6.4 ....

**Comment by Hopding** [comment]
Yes, that's the latest stable release. But version [`1.0.0-beta.3`](https://www.npmjs.com/package/pdf-lib/v/1.0.0-beta.3) is out. I plan to promote it to `1.0.0` (non-beta) this weekend.

**Comment by Hopding** [comment]
But again, you can use `pdfDoc.createPage([595.28, 841.89])` in the meantime.

**Comment by mikmikmik** [comment]
So is this implemented? I can't see how to use millimeters to define position also.

**Comment by MickL** [comment]
Yes :) Docs dont show it so it was not clear to me:

```
doc.addPage(PageSizes.A4);
```
