### ISSUE TITLE
Uploading to firestore  doesn't work

### ISSUE THREAD

**Issue by wann100** [Hopding/pdf-lib#154]
I've tried to upload this generated pdf to the firestore and it doesnt work!

I tried using .save() to submit the byte file  to firestore. The file uploads but when I open it pdf reader doesn't recognize it

and  tried to use base64(data_url) and firebase doesn't recognize that string either

Code to create pdf
```
export default async function ToPdf(data,fontSize,appointmentid)
{
  var holddescriptions ='';
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage();
  //const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman)
//const page = newPdf.addPage()
//alert("Im doing  more and more stuff");

 
  for (const key of Object.keys(data)) {

    if(data[key].checked ){
   await  page.drawText(data[key].Description);
    }
  
     
  }

  const pdfDataUri = await pdfDoc.save();
  await uploadcompletedChecklist(pdfDataUri,appointmentid);

}

```

**Comment by Hopding** [comment]
Hello @wann100! I'm not too familiar with Firestore, so I can't say where exactly the problem lies. The first thing I'd suggest that you do is download the PDF file directly from your app to your machine (skipping Firestore). That should help narrow down the scope of the problem.

Is this a web app (frontend) or a NodeJS service? If its a web app, you can render the PDF in an iframe or trigger a download (e.g. with [`download.js`](http://danml.com/download.html)). If it's a Node service, you can write it directly to the file system. 

Please let me know what you find, and we can go from there.

**Comment by wann100** [comment]
Hey thanks for the reply, I downloaded the base64 and data_url and the uni, when I use online decoders it all seems to work, the only error  one of the sites told me was with application/pdf.
I also posted a thread on the firebase google group about it to see if it's on their end.

Next I will attempt to download the file(But React Native is glitchy so we will see)

**Comment by Hopding** [comment]
If you're using React Native, you might find [this code](https://github.com/Hopding/pdf-lib/blob/master/apps/rn/src/tests/assets.js#L6-L18) to be a helpful reference when trying to write the file.

**Comment by wann100** [comment]
Thanks, I've tried the route you pointed to but unfortunately I am using expo and rn-fetch-blob doesnt seem to work

**Comment by wann100** [comment]
works with your base64 but it looks like im just making the data_url and then getting the blob

and this only works on IOS =(
```
await fetch('data:application/pdf;base64,' + file).then(res => res.blob()).then(blob => {
    ref.put(blob).then(snapshot => {
      // ... success
    })
  })

  }
```

**Comment by Hopding** [comment]
Hello @wann100. My apologies for the delayed response. Did you make any progress resolving this?

**Comment by wann100** [comment]
Hi still have no solution! It works fine when Im using an iphone to upload the base64 but with android it just doesn't work! I believe it's an react native android error. 

I looked for nearly a week and still have not found a solution

**Comment by Hopding** [comment]
Hmm. I agree, it seems likely to be a React Native problem. What exactly do you mean by "just doesn't work"? Are you getting an actual error, or does it just hang on you?

Also how large is the PDF you are working with? I'd recommend trying your code with a very simple 1 page PDF containing a short string of text. It's possible your issue is related to transferring large amount of data over React Native's bridge, which I've found Android doesn't always handle well.

**Comment by wann100** [comment]
Hey,
I tried to upload a simple empty file but on android it doesnt work. It doesnt hang it just doesn't throw an error and seems to work but never uploads on android, it is the react native bridge/Android but when i run the same app on my ios simulator it seems to work!

Oh by the way this thing is pretty awesome!

**Comment by Hopding** [comment]
I'm afraid I don't have much else to suggest on this issue. It certainly doesn't sound like an issue with `pdf-lib`. From what you describe, I suspect it is an issue in your upload code. Or perhaps the library that you are using to perform the upload.

I'm glad you're enjoying the library! Sorry I couldn't be of more help on this. I wish you luck getting it figured out 🍀
