### ISSUE TITLE
extract and replace image

### ISSUE THREAD

**Issue by xh4010** [Hopding/pdf-lib#175]
Hi Hopding
Thank you first, your project is too great.

I have this special request: I need to extract the original image from the PDF, perform color correction, and then write the corrected image back to the PDF, and the size position remains the same.
I don't know if pdf-lib can do it: extract the image, replace the image (the size position remains the same)
In this [issue](https://github.com/Hopding/pdf-lib/issues/83), extracting images seems to be possible, I will test it further.
How do I replace the image?

Another way found on the web:
Https://arunmozhi.in/2019/01/29/replacing-image-in-a-pdf-with-python

thank you very much.

**Comment by xh4010** [comment]
Hi

After testing, it is achievable, and the following problems still exist:
The transparent picture has two images in the PDF, one original image, one mask, reference to the [issue](https://github.com/Hopding/pdf-lib/issues/83) export PNG, found that there is a problem, the mask picture is blank, open it with photoshop, the error 'Not a PNG file', the suffix Can be opened after changing to jpg

Regarding the replacement image, I replaced indirectObject.contents directly with the new image, and the saved file is correct. I don't know if this method will cause other problems.

Test file:  [extract-replace-images.zip](https://github.com/Hopding/pdf-lib/files/3555202/extract-replace-images.zip)

```
npm install
node index.js
```
Take out the image and save it as jpg. The image with transparency looks weird and there is a problem with the mask image.

thanks a lot

**Comment by xh4010** [comment]
In addition, I used pdftk to extract the comparison, the file size did not increase, this is a good thing, but I found that \Info lost after pdfDoc.save:
![compare](https://user-images.githubusercontent.com/6165932/63938464-6bdc8f80-ca97-11e9-86ff-1a2afdf8de6c.jpg)

**Comment by Hopding** [comment]
Hello @xh4010!

Unfortunately, pdf-lib does not currently provide any high level APIs for image extraction or replacement. This does not mean that these things cannot be done with pdf-lib. It's just that they require you to implement a fair amount of low-level code on your own, which requires a fairly in-depth knowledge of the structure of PDFs and their image format.

The example I provided in https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843 provides a rudimentary implementation of image extraction that works for _some_ types of images from a PDF document. The issues you are encountering here appear to stem from the fact that the images in your document require additional processing logic to extract correctly. 

However, as I mentioned in https://github.com/Hopding/pdf-lib/issues/224#issuecomment-568545182, I simply do not have the time to implement this additional logic myself. But there are good reference implementations in other libraries (such as the [`PDFImage`](https://github.com/mozilla/pdf.js/blob/master/src/core/image.js#L23-L709) from [`pdf.js`](https://github.com/mozilla/pdf.js)) should anybody be interested in implementing it themselves.

As for the last issue that you mentioned (losing the `Info` entry in the new file), this has been fixed in `pdf-lib@1.0.0`. So if you update to that version (which does include a number of [breaking API changes](https://github.com/Hopding/pdf-lib#migrating-to-v1)), you will no longer encounter this issue.

I'm sure this isn't exactly the answer you were looking for. I wish I could be of more help with this. But arbitrary image extraction just isn't super easy to do in arbitrary PDF files with pdf-lib right now. I hope this changes in the future though. I'd love to provide functionality that makes this easy and straightforward to achieve.

**Comment by brianjbowers** [comment]
Has anyone gotten the file I/O method here to work https://arunmozhi.in/2019/01/29/replacing-image-in-a-pdf-with-python ? I'm getting "'charmap' codec can't decode byte" and other unicode errors trying to read the uncompressed PDF. Thanks in advance for any advice!

**Comment by Sfinx** [comment]
> Hi
> 
> After testing, it is achievable, and the following problems still exist:
> The transparent picture has two images in the PDF, one original image, one mask, reference to the [issue](https://github.com/Hopding/pdf-lib/issues/83) export PNG, found that there is a problem, the mask picture is blank, open it with photoshop, the error 'Not a PNG file', the suffix Can be opened after changing to jpg
> 
> Regarding the replacement image, I replaced indirectObject.contents directly with the new image, and the saved file is correct. I don't know if this method will cause other problems.
> 
> Test file: [extract-replace-images.zip](https://github.com/Hopding/pdf-lib/files/3555202/extract-replace-images.zip)
> 
> ```
> npm install
> node index.js
> ```
> 
> Take out the image and save it as jpg. The image with transparency looks weird and there is a problem with the mask image.
> 
> thanks a lot

It is works if the sizes of the replace and original image are the same but shows zigzags if the size is different. I guess the width & height of the replaced image must be corrected at PDFRawStream object. Can anybody tell me how to do this ? The object itself looks like :

```
PDFRawStream {
  dict: PDFDict {
    dict: Map(9) {
      [PDFName] => [PDFNumber],
      [PDFName] => [PDFName],
      [PDFName] => [PDFArray],
      [PDFName] => [PDFName],
      [PDFName] => [PDFNumber],
      [PDFName] => [PDFNumber],
      [PDFName] => [PDFName],
      [PDFName] => [PDFName],
      [PDFName] => [PDFNumber]
    },
    context: PDFContext {
      largestObjectNumber: 169,
      header: [PDFHeader],
      trailerInfo: [Object],
      indirectObjects: [Map]
    }
  },
  contents: ....
```

The content is replacing by new one, But how to correct the width/height ?

Thanks !

**Comment by Sfinx** [comment]
Solved by:

```
for (const [key, value] of newRef.dict.dict.entries()) {
    ref.dict.set(key, value)
  }
```

**Comment by gioppoluca** [comment]
@Sfinx  and @xh4010 can you share how you managed to replace the image?

**Comment by gioppoluca** [comment]
I've looked at the @xh4010 example, but I'm trying to do things in the browser and not in node.  The image turns out to be blank
