### ISSUE TITLE
drawText not working on specific file

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#194]
Hi Andrew!
I've recently integrated all your changes from v1.0.1, and it's looking great!  We're having a problem writing text to this file specifically, I'm not sure if we previously submitted this to you or not.  drawText() seems to succeed, but no text is written.  Please let me know if you have any questions.
Thanks again!

[bookmark sample.pdf](https://github.com/Hopding/pdf-lib/files/3627882/bookmark.sample.pdf)

**Comment by GautierT** [comment]
Hi !

It's probably because this file seems to be protected : 
![image](https://user-images.githubusercontent.com/6089653/65243943-c3e04200-dae9-11e9-9f82-808d786a5cf1.png)
(It's in french but as you can see in the window title "(PROTEGE)" means "PROTECTED" and the detail of the document indicate a protection by password.

**Comment by Hopding** [comment]
Hello @kevinswartz! @GautierT is correct - this document is encrypted. And, unfortunately, `pdf-lib` does not currently support encrypted documents ([read more](https://github.com/Hopding/pdf-lib#encryption-handling)).

**Comment by kevinswartz** [comment]
Thanks guys, I see that now.  It wasn't failing in the way I expected, but I figured it out.
