### ISSUE TITLE
Creating big PDF - JavaScript heap out of memory

### ISSUE THREAD

**Issue by MikeMnD** [Hopding/pdf-lib#197]
It's simple problem.
I want to create a PDF with 20k pages.

If the PDF is with 10k node.js loads in memory the `Uint8Array` and the results from
`pdfDoc.save()` is saved with `this.writeStream.write();`

`const pdfBytes = await this.pdfDoc.save();`

await is needed since it get's only promise as result and not the Writer instance...

Looking in to the source of pdf-lib it seams to use stream for save()... 
According to: 
```
export interface SaveOptions {
  useObjectStreams?: boolean;
  addDefaultPage?: boolean;
  objectsPerTick?: number;
}
```

Still in the save method:

```
await this.flush();

const Writer = useObjectStreams ? PDFStreamWriter : PDFWriter;
return Writer.forContext(this.context, objectsPerTick).serializeToBuffer();
```

So the Uint8Array is recieved only after all 20k pages... are added.

Any suggestions how to go with this use case of adding pages and writing the file to theserver at the same time without making the heap out of memory ?

**Comment by MikeMnD** [comment]
To prevent questions of type why do you need 10k pages in one pdf file: [Here a possible explanation](https://answers.acrobatusers.com/Maximum-number-of-pages-in-a-pdf-q215428.aspx)

**Comment by Hopding** [comment]
Hello @MikeMnD!

`pdf-lib` is currently limited in its ability to modify (or create) extremely large documents. This is because, as you noted, everything is performed on the heap without any sort of I/O streaming (see #239). Thus, the size of documents that can be manipulated is limited by the amount of memory available to the JavaScript engine. 

That being said, there's no reason this couldn't be changed. It should be possible for `pdf-lib` to support I/O streaming. This would provide a number of obvious benefits, including support for creating/modifying documents of arbitrary size.  

However, as I mentioned in #239, there are a number of more pressing issues I need to address before I get around to this. But if anybody would be interested in implementing this themselves, I'd be more than happy to provide guidance and answer questions!

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by wdelmas** [comment]
pdf-lib loads entire documents into memory with no streaming support. For your scenario consuming 6GB+:

**Why it happens:** Each page copies font subsets, embedded images get duplicated rather than referenced. The library wasn't designed for batch processing.

**Workarounds:**

1. **Process in batches** — Create 20 small PDFs, merge at the end
2. **Force GC** — Set references to `null`, call `global.gc()` if running Node with `--expose-gc`
3. **Worker threads** — Spawn separate processes that die after each batch (memory gets freed with process)

For high-volume scenarios, consider whether you need pdf-lib at all. If you're generating from HTML, a headless browser or API service handles memory management for you.
