### ISSUE TITLE
[Feature Request]: Preserve bookmarks when copying pages

### ISSUE THREAD

**Issue by GreenRaccoon23** [Hopding/pdf-lib#218]
Currently, `PDFDocument.copyPages()` does not copy bookmarks.

This would be a useful feature. It would enable users to concatenate PDFs while preserving their bookmarks.

Here is an example which copies file `input.pdf` and saves it as `output.pdf`. (This is a modification of the [Copy Pages example](https://github.com/Hopding/pdf-lib#copy-pages).)

```js
import { PDFDocument } from 'pdf-lib'
import * as fs from 'fs'

// Create a new PDFDocument for the destination PDF
const dstDoc = await PDFDocument.create()

// Read source PDF
const srcBytes = fs.readFileSync(__dirname + '/input.pdf')
const srcDoc = await PDFDocument.load(srcBytes)

// Copy pages from source PDF
const srcPageIndices = srcDoc.getPageIndices()
const dstPages = await dstDoc.copyPages(srcDoc, srcPageIndices) // bookmarks are lost here

// Add copied pages to destination PDF
dstPages.forEach(function(dstPage) {
	dstDoc.addPage(dstPage)
})

// Create destination PDF file
const dstBytes = await dstDoc.save()
fs.writeFileSync(__dirname + '/output.pdf', dstBytes)
```

After running this, `output.pdf` does not have `input.pdf`'s bookmarks.

**Comment by Hopding** [comment]
Hello @GreenRaccoon23! 

I assume when you say bookmarks that you're referring to the nested outline rendered in a side panel of most PDF readers. For example:

<img width="694" alt="Screen Shot 2019-10-15 at 2 25 06 PM" src="https://user-images.githubusercontent.com/10351828/66863035-cce0f980-ef57-11e9-967d-a2adfd584545.png">

I agree that this would sometimes be a useful feature. This is somewhat related to https://github.com/Hopding/pdf-lib/issues/159, as the document outline is stored in the document's catalog object. Support for cloning or otherwise manipulating catalog properties is an area in which pdf-lib is somewhat lacking at the moment. 

I think that the best way to approach this would probably be to expose an API to explicitly copy the document outline (or parts of it), e.g. `PDFDocument.copyOutline(...)` and allow them to be selectively added to the destination document. This would be more inline with how `PDFDocument.copyPages(...)` itself works.

**Comment by montekaka** [comment]
Can I get the Bookmarks?
thanks

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
