### ISSUE TITLE
AcroField checkbox problem with the check status

### ISSUE THREAD

**Issue by zepekenio** [Hopding/pdf-lib#228]
Hi,
I have a problem with editing an existing file.
When i want to check a checkbox on my pdf file everything is fine when i open the generated pdf on my computer with basic viewer software.
But when i open in adobe reader, the checkbox are unchecked.
Its very strange.
I use V1.2.1 

the code for checking checkbox : 

`field.set(PDFName.of('V'), PDFName.of('Yes'));`
`field.set(PDFName.of('AS'), PDFName.of('Yes'));`

Is someone have any ideas of the cause ?

**Comment by samneace1212** [comment]
I'm having the same issue with check boxes and also with text fields, I'm just using the example project downloaded from here. I tested it on Acrobat DC and Foxit reader, the same issue.

**Comment by Hopding** [comment]
Hello @zepekenio and @samneace1212! I've updated the example in #109 to resolve this issue. Please see my comment [here](https://github.com/Hopding/pdf-lib/issues/109#issuecomment-568484109).

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFCheckBox.check`](https://pdf-lib.js.org/docs/api/classes/pdfcheckbox#check) method is of particular relevance to this issue.
