### ISSUE TITLE
How can I get a local pdf?

### ISSUE THREAD

**Issue by Wippe** [Hopding/pdf-lib#234]
I'm getting started with this API, and I'm having a hard time creating code that takes a PDF that's ready for the program package and displays it on a screen on the electron.

**Comment by Hopding** [comment]
Hello @Wippe! pdf-lib cannot render PDFs. It’s designed to create and modify them. Rendering is another thing entirely. But I would suggest you look into using Mozilla’s PDF.js library. It’s designed to render PDFs to the DOM. This guide might help you: https://www.pdftron.com/blog/electron/how-to-build-an-electron-pdf-viewer/

**Comment by yc-cui** [comment]
> Hello @Wippe! pdf-lib cannot render PDFs. It’s designed to create and modify them. Rendering is another thing entirely. But I would suggest you look into using Mozilla’s PDF.js library. It’s designed to render PDFs to the DOM. This guide might help you: https://www.pdftron.com/blog/electron/how-to-build-an-electron-pdf-viewer/

Hi  @Hopding ! `pdf.js`  doesn't support annotations ([https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#is-it-possible-to-add-annotations-to-a-pdf](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#is-it-possible-to-add-annotations-to-a-pdf)) .  `pdf-lib` is perfect for annotations, is it possible to integrate `pdf-lib` and `pdf.js` so that I can render pdf using `pdf.js` and annotate pdf using `pdf-lib`?
