### ISSUE TITLE
[Feature Request]: Allow reading the underlying values of `PDFObjects`

### ISSUE THREAD

**Issue by MOZGIII** [Hopding/pdf-lib#238]
`PDFString` has a `value` field, but it's private. How can I read the actual value of a `PDFString`?
`toString` doesn't do that - it wraps the value with `(` `)`.

P.S. It'd be useful to add the `AcroForm` filling example as part of the test suite.

**Comment by Mogztter** [comment]
I guess you are using TypeScript because, even though the field is private, I can read the value using the `value` field in JavaScript. 

But I agree it's useful to get the value.

**Comment by MOZGIII** [comment]
I am using TypeScript, though that makes a little difference. :smile: I'm currently using a workaround with reading from the `value` filed too, but the API is definitely broken.

**Comment by Hopding** [comment]
Hello @MOZGIII! The API does not currently provide a way to access the underlying values for any of the [`PDFObject` subclasses](https://github.com/Hopding/pdf-lib/tree/master/src/core/objects). The rational for this design choice was to ensure that the underlying values are not mutated in unsupported ways that corrupt the object. And at the time, I wasn't planning for scenarios where values would need to be read out of the subclasses.

However, I can definitely see how this is inconvenient. Especially when working with Acroforms. It should be sufficient to simply mark those fields as `readonly` (rather than `private readonly`) . Although, a bit more work might need to be done for the subclasses whose underlying values are themselves mutable (e.g. [`PDFArray`](https://github.com/Hopding/pdf-lib/blob/master/src/core/objects/PDFArray.ts)).

If anybody would like to submit a PR for this, I'd be happy to accept it. Otherwise I'll try to work on this after addressing some of the outstanding bugs.

**Comment by MOZGIII** [comment]
Actually, for some subclasses the API does allow access to the value:

https://github.com/Hopding/pdf-lib/blob/8b7304d96a43a843894e3e951823616675773627/src/core/objects/PDFNumber.ts#L17-L19

I was surprised it's allowed for `PDFNumber`, but not allowed for `PDFString`.

There's no way to prevent the reader of the value from modifying it. `readonly` just prevents from reassigning the field (i.e. it's like using a `const` instead of `let`) - the internal mutability of the values in not restricted.
The only real way to prevent corruption is to copy the object. Though it might be an overkill.

I suggest simply adding an equivalent `value(): string`  getter to the `PDFString` object. I think it's good enough level of protection. It has the benefit of being functionally expressive at both TypeScript and JavaScript code.
I can submit a PR if you'd like.

**Comment by Hopding** [comment]
None of the subclasses exposed read access originally. However, as you observed, read access was later added for a couple of the subclasses ([`PDFNumber`](https://github.com/Hopding/pdf-lib/commit/829fdf3a9533a3b182c3305c979839ac49150888#diff-7810a79f28df5199f64cf4f1e4ed7b13) and [`PDFName`](https://github.com/Hopding/pdf-lib/commit/829fdf3a9533a3b182c3305c979839ac49150888#diff-57541c6caf37b52d9a03576dfff111ee)). But only when I found it necessary for internal usage by pdf-lib itself.

You're correct that `readonly` doesn't prevent mutating the field itself. But for subclasses that use primitive types (like `string`, `number`, and `boolean`) that doesn't matter, because primitive types are themselves immutable. But for subclasses like `PDFDict` and `PDFArray` that _are_ backed by mutable types, marking them as `readonly` is not sufficient. For these classes, I do think that copying the object would be the best approach.

I'd be willing to accept a PR that exposes the backing values for all the `PDFObject` subclasses via getter methods, so long as the mutable values are cloned before being returned from the getter.

**Comment by Hopding** [comment]
Version [`1.5.0`](https://www.npmjs.com/package/pdf-lib/v/1.5.0) is now published. This version contains new accessor methods on `PDFObject` subclasses to access their underlying values. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.5.0).

You can install this new version with npm:

```
npm install pdf-lib@1.5.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.5.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.5.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.5.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.5.0/dist/pdf-lib.min.js

**Comment by MOZGIII** [comment]
This is great, thx!
