### ISSUE TITLE
Support or demo for writing PDF using Streams

### ISSUE THREAD

**Issue by estebanroblesluna** [Hopding/pdf-lib#239]
Hi @Hopding ,
I have seen in the code that the term Stream is being used multiple times so I'm wondering what type of support do you have for writing PDF to the filesystem using Streams (and by Streams I mean its concept in any programming language).
I'm looking at the basic examples where images are loaded into memory and they seem to be loaded and then referenced when they are embedded in PDFs. I'm wondering if you have a solution that would minimize the memory footprint
Thanks
Esteban

**Comment by Hopding** [comment]
Hello @estebanroblesluna! 

There are a couple of different types of stream objects in pdf-lib's codebase. The ones you are referring to are probably used internally by pdf-lib's parser. However, they are backed by in-memory buffers - not async i/o streams. 

This would be a nice feature to offer in pdf-lib though. And by lowering the memory footprint, it would enable larger documents to be manipulated/generated (e.g. https://github.com/Hopding/pdf-lib/issues/197). However, there are a number of other features/issues I am hoping to address first. But, I'd be happy to work with anybody interested in creating a PR for this!

**Comment by taxilian** [comment]
Well, it definitely wouldn't be a complete solution, but you could reduce the footprint by a fair amount just by updating the PDFWriter to be able to write directly to a WritableStream instead of requiring it to write to a UInt8Array. 

That wouldn't do anything about all the objects it is serializing, but it would save the size of the buffer being created when it writes and let you send the data directly back to the browser or to a file.

Thoughts? Seems like it would be a really easy change.

**Comment by clakech** [comment]
@taxilian I agree. could you craft a PR please? It is not so easy for me to do so

**Comment by DynamicArray** [comment]
@taxilian @clakech Did anyone make the PR or have a go at the code for writing directly to a stream?

If not, I'm going to give it a go.

**Comment by dbartholomae** [comment]
I see that this is closed. Was this implemented?

**Comment by hoonsubin** [comment]
What's the status of this issue? Similar to the issue mentioned in https://github.com/Hopding/pdf-lib/issues/197, I'm also getting an out-of-memory error when I invoke the `.save` method.
