### ISSUE TITLE
Checkbox Default Appearance Stream

### ISSUE THREAD

**Issue by cshenks** [Hopding/pdf-lib#271]
### Description
Because `pdf-lib` does not specify a default appearance stream for the checkbox on state, users who have tried to set checkbox values and export see empty fields (See #228). Let's add a default appearance stream for the checkbox on stream.

@Hopding Do you have any ideas for the default appearance stream? Maybe it should be similar to the default checkbox styles for the annotation layer in `pdfjs`?

### Tasks
- [ ] Create default appearance stream for `CheckBox` field on states.

### Dependencies
- [ ] Requires #269

**Comment by Hopding** [comment]
@cshenks I think modeling the default appearance stream after `pdf.js` styling is fine. We could also reference Acrobat's default styling (visually, of course, as the code is not available). The main thing to be aware of is that `pdf.js` uses [CSS for its AcroForm field styling](https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.css). But, of course, pdf-lib does not do any sort of rendering like this. So we'll need to actually construct an `AP` XObject with PDF operators to build the appearance stream.

It's also worth noting that the reason users saw empty fields in #228 was because they were not setting `NeedAppearances` to `true` on the AcroForm. When this field is set correctly, the fields render just fine (see https://github.com/Hopding/pdf-lib/issues/109#issuecomment-568484109).

This brings up an interesting question of whether or not pdf-lib should write appearance streams by default (see https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999 for some more detail on this) when AcroFields are created/modified. I tend to favor not writing out appearance streams by default. This would just mean that pdf-lib would need to automatically set `NeedAppearances` to `true` on the AcroForm when fields are modified. We'd also need to remove any existing appearance streams on the modified fields (though this is necessary even if we generate our own).

However, as I said in https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999, there are still perfectly valid reasons to generate an actual appearance stream. And it would be nice if pdf-lib could do this automatically upon the user's request. So I think this issue is still valid (and we'll want to do something similar for all the other AcroField types).

**Comment by cshenks** [comment]
> @cshenks I think modeling the default appearance stream after `pdf.js` styling is fine. We could also reference Acrobat's default styling (visually, of course, as the code is not available). The main thing to be aware of is that `pdf.js` uses [CSS for its AcroForm field styling](https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.css). But, of course, pdf-lib does not do any sort of rendering like this. So we'll need to actually construct an `AP` XObject with PDF operators to build the appearance stream.
> 
> It's also worth noting that the reason users saw empty fields in #228 was because they were not setting `NeedAppearances` to `true` on the AcroForm. When this field is set correctly, the fields render just fine (see [#109 (comment)](https://github.com/Hopding/pdf-lib/issues/109#issuecomment-568484109)).
> 
> This brings up an interesting question of whether or not pdf-lib should write appearance streams by default (see [#205 (comment)](https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999) for some more detail on this) when AcroFields are created/modified. I tend to favor not writing out appearance streams by default. This would just mean that pdf-lib would need to automatically set `NeedAppearances` to `true` on the AcroForm when fields are modified. We'd also need to remove any existing appearance streams on the modified fields (though this is necessary even if we generate our own).
> 
> However, as I said in [#205 (comment)](https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999), there are still perfectly valid reasons to generate an actual appearance stream. And it would be nice if pdf-lib could do this automatically upon the user's request. So I think this issue is still valid (and we'll want to do something similar for all the other AcroField types).

I see. I misunderstood the issue with `NeedAppearances` since I've had issues getting certain checkboxes to appear checked after marking them using the example script in https://github.com/Hopding/pdf-lib/issues/109. The sample I've been trying is 
[f1099msc.pdf](https://github.com/Hopding/pdf-lib/files/4003828/f1099msc.pdf). In that case in particular, setting the value and appearance state to '`Yes'` did not work. It seems that in some cases the appearances dictionary has keys that aren't what you might expect, so no matching appearance stream is found for the appearance state value. I think it might be a good idea to safeguard against this by providing a fallback appearance stream and setting the appearance state accordingly if no match is found.

**Comment by Hopding** [comment]
@cshenks I took a look at the document you shared ([f1099msc.pdf](https://github.com/Hopding/pdf-lib/files/4003828/f1099msc.pdf)). There are a couple of things going on that make this document "special":

* The `AcroForm` dictionary has an `XFA` entry in addition to its `Fields` entry. This essentially means that it contains two versions of its form. One in the normal, standard AcroForms format. And a second one in the annoying, complicated XFA format. This means that filling out the standard forms (under the `Fields` array) will have no visible effect when viewed in Acrobat, because Acrobat favors `XFA` forms whenever they're both present. But it's pretty much the only reader that does this. Most readers don't even try to handle XFA due to its complexity. In fact, XFA is actually deprecated in PDF 2.0. You can read more in this great stackoverflow answer: https://stackoverflow.com/a/54733836.
* The "check boxes" at the top of the pages are not actually check boxes at all. They are radio buttons. Visually, check boxes and radio buttons look the same. But their underlying structure and behavior is rather different. In particular, check boxes always have a simple, binary `/Yes` or `/Off` state. Radio buttons also have an `/Off` state, but they do not have `/Yes` states. Instead, they store the name of the currently selected radio button in the group. Hence the `/1` and `/2` values for the `/AS` and `/AP` entries that you can see in the document you shared. You can read more about radio buttons in section **12.7.4.2.4 Radio Buttons** of the PDF spec.

These are both great examples of more complicated scenarios that we'll want to handle in the AcroForms API so that users don't need to deal with this weirdness.

I think the best solution to the `XFA` issue is to simply delete the `XFA` entry. This way Acrobat will be forced to read the standard form. I definitely do not want to try to built in a mechanism to create/populate XFA forms. That'd be a nightmare of additional complexity that just isn't worth it, especially since XFA forms are deprecated now.

As for the radio buttons, that'll just be a matter of detecting when a given field is part of a radio button group or just a standalone checkbox. And we'll have to deal with it accordingly. I'm guessing that the code for handling radio button groups will be more complicated than the code for handling any of the other form field types. But that's just due to the annoying tree structure the PDF spec defines them with.

**Comment by punisher97** [comment]
Hi, i read export  value from Appearance States to get value "/Yes", its good or bad to performance?
for example if PDF create in language spanish default export Value if "Sí" pdf-lib read as "S#ED", to avoid this issue, i get appearance state from /AP << /N << /Yes 8 0 R

I only use simple checkbox or radio buttons, no groups
Thanks:

```typescript
  const state = value
    ? //@ts-ignore
      (Array.from(
        //@ts-ignore
        acroField
          .lookupMaybe(Constants.AP, PDFDict)
          ?.get(Constants.N)
          //@ts-ignore
          .dict.keys(),
      )[1] as PDFName)
    : Constants.Off;
  acroField.set(Constants.V, state);
  acroField.set(Constants.AS, state);
```

**Comment by Hopding** [comment]
@punisher97 If I understand correctly, it sounds like your approach is fine.
