### ISSUE TITLE
Typescript / problem with --isolatedModules

### ISSUE THREAD

**Issue by crazyx13th** [Hopding/pdf-lib#272]
Hi there,

I always got
```
ERROR in C:/workspace/project/node_modules/pdf-lib/cjs/core/operators/PDFOperatorNames.d.ts(76,16):
TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

If I remove `const` all i fine!

Maybe you can do this too?
Thanks!

Greetings
crazyx13th

**Comment by Hopding** [comment]
Looks like the only solution to this issue is to avoid exporting `const enum` objects. Fortunately the only `const enum` in the pdf-lib codebase is here:

https://github.com/Hopding/pdf-lib/blob/8346da359c1c35089b2d02af07d29228e89482a3/src/core/operators/PDFOperatorNames.ts#L1

Converting this to a plain `enum` should be fine. This seems like the only viable solution anyways.

@crazyx13th if you would like to submit a PR for this, I'd be happy to merge it. Otherwise I'll make this change when I have some time.
