### ISSUE TITLE
Transparent rect background

### ISSUE THREAD

**Issue by prosenjit-manna** [Hopding/pdf-lib#280]
Unable to set transparent background color to a rectangle.  Found only three color https://pdf-lib.js.org/docs/api/enums/colortypes

How I can set the transparent background color?

**Comment by Hopding** [comment]
Hello @prosenjit-manna! Adjusting the opacity of shapes (or text) is not currently possible with pdf-lib's high level APIs. This issue is currently being tracked in https://github.com/Hopding/pdf-lib/issues/210, so I'm going to close this one to keep things organized.

It's worth noting that it's not impossible to do this with pdf-lib. There just aren't any high level APIs for it. If you want to dig into some lower-level stuff, you can certainly achieve it. I'm afraid I don't have time to write up an example right now, but you could take a look at how `pdfkit` does this if you'd like to give it a shot: https://github.com/foliojs/pdfkit/blob/master/lib/mixins/color.js#L109-L144.

**Comment by prosenjit-manna** [comment]
Thanks for your information.

**Comment by Thymo** [comment]
@prosenjit-manna As a temporary solution, you can manually create a pdf file which contains the rectangle with a semi-transparent background, and then add this using the drawPage function:
`
const pdfData = fs.readFileSync(__dirname+'/rectangle.pdf');
const [rectanglePdf] = await pdfDoc.embedPdf(pdfData);
page.drawPage(rectanglePdf, {
                x,
                y,
                width ,
                height,
            });
`

**Comment by Hopding** [comment]
Version [`1.8.0`](https://www.npmjs.com/package/pdf-lib/v/1.8.0) is now published. It contains `opacity` and `borderOpacity` options for all page drawing methods (thanks @soadzoor!). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.8.0).

You can install this new version with npm:

```
npm install pdf-lib@1.8.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.8.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.8.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.8.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.8.0/dist/pdf-lib.min.js
