### ISSUE TITLE
How can download pdf as base64, after user have filled form fields ?

### ISSUE THREAD

**Issue by mdhanju** [Hopding/pdf-lib#346]
<img width="491" alt="Screen Shot 2020-02-05 at 11 07 49 PM" src="https://user-images.githubusercontent.com/7625083/73913640-6700e080-486c-11ea-8f96-2e9c20c7ed3f.png">

How can i down form as base64 when user have filled it.

**Comment by jumpypixels** [comment]
Similar question here. I can save the program filled in field but not user filled field.

**Comment by jumpypixels** [comment]
I think I understand now. There's no way pdf-lib can handle input by an user since the rendering is done by the browser. pdf-lib can create/load, manipulate and deliver to browser, it cannot get any feed back from a browser

**Comment by Hopding** [comment]
Hello @mdhanju and @jumpypixels! What @jumpypixels observed is correct. pdf-lib handles creating and loading PDF files. It's up to you to figure out how to get a PDF file into pdf-lib, as well as what you wish to do after saving it in pdf-lib. pdf-lib is not designed to render PDF files. If you are rendering a PDF in the browser via an iframe (or some other method), pdf-lib has no built-in way to interact with edits the user makes in the iframe. However, if you have some other way of knowing what the user has done to edit the PDF (e.g. by rendering an HTML form instead of a PDF), you could use pdf-lib to map these changes into PDF modifications (see: https://github.com/Hopding/pdf-lib/issues/48).
