### ISSUE TITLE
First line of the example script on the home page seems off.

### ISSUE THREAD

**Issue by sgbeal** [Hopding/pdf-lib#347]
From this project's home page:

![image](https://user-images.githubusercontent.com/235303/74031764-a33e5900-49b2-11ea-8909-f5cefe234412.png)

Certainly the first line in the red block is not intended?

**Comment by Hopding** [comment]
Hello @sgbeal!

The code is actually correct. If you save the example snippet as an HTML file and open it in your browser you should see it works as expected. Though I can certainly understand your confusion. The reason that the `createPdf` function can be called prior to its definition in the code is due to [function hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting).
