### ISSUE TITLE
Visual Regression Testing for integration-test-PDFs

### ISSUE THREAD

**Issue by tessi** [Hopding/pdf-lib#353]
Hello @Hopding :wave:

While implementing my PR about embedding PDF pages, I touched our integration tests. I really like that they give nice visual output, are tested across devices/platforms, and provide usage examples for `pdf-lib`. However, I found some limitations with that approach:

* running these test requires manual inspection of the generated PDFs
* it is hard to know whether the generated PDF is actually good (there may be small changes that are not easy to spot for the human eye or new contributors)
* it takes time to run and makes contributing to this project harder
* it is easy to forget to run them

I would like to propose an additional way to run the integration tests. This would look like this:

* generate all PDFs with nodejs and save the PDF files to disk in some working directory (e.g. `test1.pdf`, `test2.pdf`)
* convert these pdfs into images (one image per page, or one big image containing all pages; e.g. `test1/page1.png`). This could be done with, for example, ghostscript:
```js
const path = require('path');
const util = require('util');
const childProcess = require('child_process');
const exec = util.promisify(childProcess.exec);

const command = `gs -dNOPAUSE -dBATCH -sDEVICE=png16m -r200 -dTextAlphaBits=4 -dDOINTERPOLATE -dGraphicsAlphaBits=4 -sOutputFile=${someWorkingDir}${path.sep}%d.png -f ${pdfFile}`;
await exec(command, { maxBuffer: 1024 * 1000 * 10 }).catch(e =>
  console.error(`Run away in panic!!1\nError: ${e}`)
);
```
* use some tool for visual regression testing to compare these images against known good images. A short google search brought up [reg-suit](https://github.com/reg-viz/reg-suit) which seems to be well maintained and quite flexible
* When run on CI and there are visual changes to the output images, [upload the diffs as CircleCI artifacts](https://circleci.com/docs/2.0/artifacts/)
* When changes to the known good images are intentional (the PR author changes the visual outcome on purpose), new good images have to be commited. During PR review we could inspect the changes using [GitHubs builtin tool for image comparison](https://help.github.com/en/github/managing-files-in-a-repository/rendering-and-diffing-images).

This would automate testing the PDFs but not running them on e.g. android. A downside is that these visual regression test, in my experience, have a tendency to be flaky (they sometimes fail, and sometimes not). But probably they will not be flaky (enough) to be an issue.

What do you think of this proposal?

To be honest, I am not sure whether I will have time to actually implement this. But I wanted to plant this idea, [inception-style](https://en.wikipedia.org/wiki/Inception) ;), in your head.

<p align="center">
<img src="https://user-images.githubusercontent.com/206108/74434591-06246a00-4e63-11ea-89c8-01a38bcd0787.gif">
</p>

**Comment by tessi** [comment]
Just want to mention that if your current workflow is good enough for you please don't feel any pressure to change it. This is just a random idea 🌷

**Comment by Hopding** [comment]
Hello @tessi! 

This is definitely an interesting idea. I considered doing something like it myself when I was initially creating the integration tests. I certainly agree that running the integration tests is a bit tedious for newcomers. However, since the time I have to work on pdf-lib is already limited, I don't think I can justify spending it on optimizing the integration tests. At the moment, there are simplify too many other things that would provide more value.

The potential for flakiness and false positives, and need for additional system-level tools/libraries is also rather concerning. The tests would also likely become more complicated, harder to maintain, and take longer to run. Especially considering that each environment would need to be able to capture these visual artifacts.

Generally speaking, it's sufficient for contributors to run just the node and browser tests. I don't really expect contributors to run the React Native tests themselves, as the system setup for them is far more nuanced. Though, I suppose I haven't documented this...

All of that being said, it's possible I'm completely wrong and that this concept could be implemented in a clean and robust way without too much additional complexity. So if anybody would like to explore some potential implementations of this, I'm happy to discuss it!

**Comment by Hopding** [comment]
I'm going to close this issue for now as I don't see this happening for awhile.

**Comment by tessi** [comment]
👍 true. thanks for the cleanup 💚
