### ISSUE TITLE
load fails if pdf is not 100% correct

### ISSUE THREAD

**Issue by pdungel** [Hopding/pdf-lib#357]
When loading pdf's, sometimes the loaded document has empty pages. After some digging I found out, that this seems to happen only in cases where the original document ist not formated  totally correct. When checking the document on https://www.metadata2go.com, there is a warning " Duplicate 'MediaBox' entry in Dictionary (ignored)".

Those pdf's where the warning occurs, are  scans produced from my xerox machine. Is there a way to work around that warning and process the document normally since I have no way to alter the method how the documents are scanned

**Comment by Hopding** [comment]
Hello @pdungel!

Would you please share some code and a sample document that I can use to reproduce the issue? Also, what version of pdf-lib are you using?

**Comment by pdungel** [comment]
thank you for your quick response, of course, here is the code and one pdf
that causes the trouble

basically I took the sample code from the github page and edited to my needs

async function merge(files) {
      const mergedPdf = await PDFDocument.create();
      for (const pdfToMerge of files) {
        const pdfBytes = fs.readFileSync(pdfToMerge);
        const pdf = await PDFDocument.load(pdfBytes);
        const copiedPages = await mergedPdf.copyPages(pdf,
pdf.getPageIndices());
        copiedPages.forEach((page) => {
          mergedPdf.addPage(page);
        });
        const mergedPdfFile = await mergedPdf.save();
        fs.writeFileSync(mergedPDF, mergedPdfFile);
      }
      files.forEach(element => {
          fs.unlink('./' + element, function(err) {
              if (err) {
                  console.log(err);
              }
          });
      });
      res.render('download', {title: 'Merging complete', type: 'merge',
link: 'download/' + mergedPDF});
    }

you can ignore the part that starts at files.forEach - this only deletes
the temporary created files. I tested the code and looked at the original
uploaded pdf (the one that i read with fs.readFileSync) which was fine, the
merdedPdf did only have an empty page.

please excuse the bad variable naming, this is due to fact that for testing
purposes I more or less took the sample code where the variable names were
almost the same as mine

i attach one of the pdf's thats causing the problem

yours peter


Am So., 16. Feb. 2020 um 23:03 Uhr schrieb Andrew Dillon <
notifications@github.com>:

**Comment by Hopding** [comment]
@pdungel I'm unable to find the PDF you shared in either this GitHub thread or my email. Would you please try sharing it again? If the document needs to remain private, please feel free to [email it to me directly](https://github.com/Hopding). Otherwise, it's best to post directly to the GitHub thread.

**Comment by pdungel** [comment]
@Hopding thanks, that you are looking into this. I don't know why the file was not attached the last time, maybe it dows not work as a mail attachment, but anyhow, here is a "not working" pdf which does not need to remain private


[notWorking.pdf](https://github.com/Hopding/pdf-lib/files/4214188/notWorking.pdf)

**Comment by Hopding** [comment]
@pdungel I was able to find and resolve the issue in #364. The PDF you shared is technically invalid (it's missing a newline in its "binary comment line"), so pdf-lib failed to parse it correctly. That's why you wound up with an empty document. However, I updated the parser to handle the issue, so it will now parse successfully. I'm hoping to do a release tonight or tomorrow. Once I do, the fix will be available to you.

**Comment by Hopding** [comment]
@pdungel Version [`1.3.2`](https://www.npmjs.com/package/pdf-lib/v/1.3.2) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.3.2).

You can install this new version with npm:

```
npm install pdf-lib@1.3.2
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.3.2/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.3.2/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.3.2/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.3.2/dist/pdf-lib.min.js
