### ISSUE TITLE
Get a list of all text and signature forms in pdf

### ISSUE THREAD

**Issue by arthabus** [Hopding/pdf-lib#386]
Hi, is it possible to list all the existing text and signature fields in an existing pdf? Maybe there is an example how to do that?

**Comment by Hopding** [comment]
@arthabus The example code I provided in https://github.com/Hopding/pdf-lib/issues/349#issuecomment-585508339 should do what you're looking for.

**Comment by arthabus** [comment]
Thanks @Hopding, this is helpful! 

Wondering if it's documented somewhere by any chance? I'm trying to understand what is the available apis for this, but can't quite fined related info in the docs (https://pdf-lib.js.org/docs/api/)

**Comment by Hopding** [comment]
@arthabus The [docs](https://pdf-lib.js.org/docs/api/) are primarily for the APIs under the [`src/api`](https://github.com/Hopding/pdf-lib/tree/master/src/api) directory. These are the high-level APIs that most pdf-lib users are after. 

However, the bulk of pdf-lib's code is actually in [`src/core`](https://github.com/Hopding/pdf-lib/tree/master/src/core) and [`src/utils`](https://github.com/Hopding/pdf-lib/tree/master/src/utils). This is where the "real" work is done. The code in [`src/api`](https://github.com/Hopding/pdf-lib/tree/master/src/api) only exists to provide a nice interface that abstracts over the gorey PDF details.

I've chosen not to publish docs for [`src/core`](https://github.com/Hopding/pdf-lib/tree/master/src/core) and [`src/utils`](https://github.com/Hopding/pdf-lib/tree/master/src/utils) because they wouldn't be helpful to most users, they would just add a bunch of noise to the docs pages. Also, I have not written doc comments or examples for these low level APIs like I have for [`src/api`](https://github.com/Hopding/pdf-lib/tree/master/src/api). (You can see [here](https://github.com/Hopding/pdf-lib-docs/blob/master/typedoc.json#L7-L8) that these directories are excluded from the generated docs).

All that being said, it's still perfectly fine to use the low-level APIs. They're public and stable, just like the high-level APIs. If you're looking to find what all is available in [`src/core`](https://github.com/Hopding/pdf-lib/tree/master/src/core) and [`src/utils`](https://github.com/Hopding/pdf-lib/tree/master/src/utils), I'd suggest pulling down the source or just browsing it on GitHub.
