### ISSUE TITLE
What is an encrypted document?

### ISSUE THREAD

**Issue by shreevatsa** [Hopding/pdf-lib#387]
Thanks for pdf-lib! I'm using it to [reorder pages](https://shreevatsa.net/mobius-print/) or [extract pages](https://shreevatsa.net/pdf-pages/). At the latter I tried to load a certain PDF today, namely the following one: http://bitsavers.informatik.uni-stuttgart.de/pdf/ibm/650/22-6060-2_650_OperMan.pdf and it failed with an error like:

> Uncaught (in promise) Error: Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways.

And if I try with `ignoreEncryption`, I get a blank page.

This PDF does seem to open fine (in other PDF viewers) without requiring any password or something like that. So I wonder: what does it mean to say that it is encrypted? Could it possibly be a bug?

(Apologies in advance for not trying the latest version of pdf-lib, and for not trying to debug further myself e.g. trying to turn the PDF into a smaller example, or looking up the PDF reference or properties…)

**Comment by Hopding** [comment]
Hello @shreevatsa!

A document is encrypted if it requires a password to open. This seems confusing at first, because you did not have to enter a password to view the document. But your PDF viewer still used a password behind the scenes. The PDF spec actually defines a _default password_ to use in these scenarios. I explain more about this [here](https://github.com/Hopding/pdf-lib/issues/134#issuecomment-509452191). 

You can't really figure out for sure if a document is encrypted with the default password in some readers. But if you open it in Acrobat you can tell:

![Screen Shot 2020-04-09 at 6 11 14 PM](https://user-images.githubusercontent.com/10351828/78948995-ce672680-7a8f-11ea-8dc8-170099f540e4.png)

Note the sections I outlined in red. They indicate the document uses the default password.

I hope this helps. Please let me know if you have any additional questions!

---

I should also note that PDF decryption support is a pretty highly requested feature (see https://github.com/Hopding/pdf-lib/issues/233). It's probably going to be the next thing I work on after finishing AcroForms support (no promises on a delivery timeline though).

**Comment by shreevatsa** [comment]
Thanks a lot for that explanation and the link (had somehow missed it earlier)... It's very clear. Thanks for taking the time to answer and for your work on pdf-lib, it's a really fine piece of software (and documentation).
