### ISSUE TITLE
Can't fill in model with pdf-lib 

### ISSUE THREAD

**Issue by cherifa-ghersi** [Hopding/pdf-lib#391]
Hello! 
 i am having an issue when I try to fill a pdf form from model that contains some text fields, but i can't see my changes in the pdf, can you help me ? i see issues with same problem but i have not find a solution .

thanks @Hopding

**Comment by BigGillyStyle** [comment]
Hi @cherifa-ghersi  I'm new to this library and am finding on my Mac that my changes to a form with text fields can be seen when viewing the resultant PDF in Chrome or Acrobat but not in Safari or Preview (I'm on Catalina 10.15.4).  What OS are you using?

Also, when I looked through all the various issues related to this problem, there was one solution that I found consistently that was required in order to make this work in the PDF viewers I mentioned above:

```
acroForm.set(PDFName.of('NeedAppearances'), PDFBool.True);
```

**Comment by BigGillyStyle** [comment]
@cherifa-ghersi I've created a similar issue here: https://github.com/Hopding/pdf-lib/issues/401  In that PR you'll see a link to the GH repo where I've had at least partial success.  Maybe that would be a good starting point for you.

**Comment by BigGillyStyle** [comment]
I was able to close my GH issue here due to a one-liner change.  Now I'm able to fill PDF text fields and have it render properly in all PDF viewers (the ones I've checked on my Mac, that is).  Sample code is here: https://github.com/BigGillyStyle/pdf-form-fill-app

**Comment by Hopding** [comment]
Hello @cherifa-ghersi!

The solution suggested by @BigGillyStyle is a good one that I'd recommend you try. However, if that solution doesn't suit your needs, there's another approach you can take that I've explained in https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999.

I hope this helps! If you're still unable to get things working then please share some sample code and a document that I can use to reproduce your issue.
