### ISSUE TITLE
Calling copyPages for each document-page duplicates embedded-fonts

### ISSUE THREAD

**Issue by TheVanDoom** [Hopding/pdf-lib#393]
I found this behaviour when I was analysing https://github.com/Hopding/pdf-lib/issues/392

```
const pdfDoc = await PDFDocument.create();
const baseDocument = await PDFDocument.load(input.pdfData);

for (idx of baseDocument.getPageIndices()) {
    const [copiedPage] = await pdfDoc.copyPages(baseDocument,[idx]);
    pdfDoc.addPage(copiedPage);
};
```

When copying a document page by page, the embedded-font is duplicated for every page, increasing the size of the document significantly (depending on the font of course). Copying all pages at once and the adding the pages one by one seems to work around this problem.

```
const baseDocumentPages = await pdfDoc.copyPages(baseDocument, baseDocument.getPageIndices());
baseDocumentPages.forEach((page) => pdfDoc.addPage(page));
```

**Comment by Hopding** [comment]
Hello @TheVanDoom! 

This is expected behavior. All necessary objects are copied anew each time you call `copyPages`. `pdf-lib` does not attempt to cache documents or reuse copied objects outside of the `copyPages` calls. It might be possible to figure out a way to do this. But in order to avoid memory leaks it would require the ability to do deep comparisons of PDF objects. And due to the structure of PDF objects, this is not a trivial thing to do.

If anybody would like to figure out a way to architect and implement a page/object copying that automatically prevents copying (or somehow eliminates writing) duplicate objects, I'd be happy to answer questions and provide advice. But since the API provides a reasonable interface that avoids the issue, I can't prioritize this over other work for the foreseeable future.
