### ISSUE TITLE
Prepending pages shows incorrect output in Google Chrome for certain pdf files (samples included)

### ISSUE THREAD

**Issue by mugli** [Hopding/pdf-lib#400]
I'm trying to merge two pdf files using pdf-lib. When I open the merged result with Google Chrome (tested in macOS), looks like the code works for most of the files but also doesn't work with certain files.

Not sure if this is a bug with the library or with the rendered in Chrome.

I have added a demo repository for demonstrating this with both working and not-working samples here: https://github.com/mugli/demo-prepending-page-to-pdf

Please let me know if there's a better way to achieve this or if there's any workaround.

**Comment by Hopding** [comment]
Hello @mugli!

I was able to get the `output-problematic.pdf` to render in Google Chrome on my mac. However, it does take a couple seconds to render. Here's a screen recording of what I see:

[output-problematic.mov.txt](https://github.com/Hopding/pdf-lib/files/4453293/output-problematic.mov.txt) 
> The `.txt` extension is to make GitHub happy. Download the file and remove the `.txt` extension to view the recording.

And here's a screen recording of the original `input-problematic.pdf` file, untouched by pdf-lib:

[input-problematic.mov.txt](https://github.com/Hopding/pdf-lib/files/4453294/input-problematic.mov.txt)
> The `.txt` extension is to make GitHub happy. Download the file and remove the `.txt` extension to view the recording.

Notice that it takes chrome a few seconds to render the `input-problematic.pdf` file. It appears to take Chrome the same amount of time to render that page whether or not it is merged with other pages in a document. 

I tried opening the `input-problematic.pdf` file in a few other readers as well (Acrobat, Foxit, and Preview). They all take noticeably longer to render that page than they do for most other documents. 

All of this being said, the problem seems to lie in the `input-problematic.pdf` you're using. The only solution here would be to somehow optimize that page to render more quickly. Perhaps reducing its size or the size of assets it relies on?

I hope this helps. Please let me know if you have any additional questions!

**Comment by mugli** [comment]
Thank you. Yes, I also think that this is one odd pdf file. I'll let you know if this happens with other files too in the future.
