### ISSUE TITLE
PDFFont.heightAtSize returns full height without a way to get y offset

### ISSUE THREAD

**Issue by jarommadsen** [Hopding/pdf-lib#407]
I am using some custom handwriting styled fonts (like https://fonts.google.com/specimen/Alex+Brush) to implement my own electronic signatures. These fonts have some pretty crazy tails on some letters. pdf-lib draws text from the baseline, above these tails. `PDFFont.heightAtSize` returns the height above and below the baseline, which on standard fonts the extra height is negligible but these handwriting fonts can add substantial amounts.

I am styling a pdf-fillable app using css which places text from the top-left corner and I am trying to get that html view to match up with the generated pdf view. In order to do that I have to calculate the height of the font and subtract it from the x/y position I placed in html to draw correctly in pdf-lib. Using the height from `heightAtSize` can overshoot the signature line up to 10 pixels depending on the font.

Is there a way to obtain the font's baseline offset or be able to draw text starting from the top left?

<img width="145" alt="Screen Shot 2020-04-13 at 4 58 14 PM" src="https://user-images.githubusercontent.com/18220195/79168843-1942b000-7da8-11ea-9bad-ed5b95603e48.png">

(The red box is the font height drawn at the same coordinates as the text. The green box uses the font size which is more accurate but still taller than the actual text from the baseline.)

**Comment by jarommadsen** [comment]
Using 3/4 of the `heightAtSize` value actually gets it suspiciously close (like I can't tell the difference between the html placement and pdf-lib now). Is it possible that the height is calculated using 3/4 above the baseline and 1/4 below it? That'd be convenient if true.

**Comment by jarommadsen** [comment]
To be more precise in my vocabulary:
![image](https://user-images.githubusercontent.com/18220195/79170535-e0f1a080-7dac-11ea-805e-9d0f5b63ea46.png)
What exactly does `heightAtSize` return? Judging by [this example](https://github.com/Hopding/pdf-lib/blob/master/assets/pdfs/examples/embed_font_and_measure_text.pdf) it seems that the assumption was that it returned the "cap height" when in reality it's returning the full type size. Is there any way of accessing the "cap height" or "descender height" or anything that might in helping with precise placement?

**Comment by Hopding** [comment]
Hello @jarommadsen!

There are two types of font embedders used internally by `pdf-lib`: [`StandardFontEmbedder`](https://github.com/Hopding/pdf-lib/blob/master/src/core/embedders/StandardFontEmbedder.ts) and [`CustomFontEmbedder`](https://github.com/Hopding/pdf-lib/blob/master/src/core/embedders/CustomFontEmbedder.ts). Since you are embedding a custom font, the `CustomFontEmbedder` is what matters most to answer your question (though the answer is similar for `StandardFontEmbedder`, but it is backed by a different library).

The `PDFFont.heightAtSize` method uses the `CustomFontEmbedder.heightOfFontAtSize` method to compute the height of your custom font:

https://github.com/Hopding/pdf-lib/blob/129b846610051a252ea0b3aa6c6856f49f6525aa/src/core/embedders/CustomFontEmbedder.ts#L71-L76

The above snippet should be pretty self-explanatory. The height is found by computing the difference between the ascender and descender of the font, or falling back to the bounding box if those properties are undefined. And, of course, the height is scaled appropriately (the division by 1000 is just due to a weird PDF specification detail).

Note that the `font` object these properties are pulled from is a [`fontkit`](https://github.com/foliojs/fontkit) object (though technically `pdf-lib` uses a fork of `fontkit`: [`@pdf-lib/fontkit`](https://github.com/Hopding/fontkit)). I do not know how `fontkit` computes those values internally. 

I see three possibilities here:
1. `fontkit` is computing the ascender/descender incorrectly for your font.
2. The font you are using does not properly specify the ascender/descender.
3. There is a different property of the `fontkit` object that `pdf-lib` should use to compute the font's height. Or perhaps just another way of computing the height that could be exposed via an additional `PDFFont` method.

**Comment by Hopding** [comment]
I'm going to close this issue for now. Please feel free to reopen if you'd like to discuss this further.

**Comment by jarommadsen** [comment]
Thanks @hopding, I appreciated the insight. Haven't had time to investigate further but the 3/4 workaround has been good enough to get by.
