### ISSUE TITLE
trying to parse invalid object

### ISSUE THREAD

**Issue by kimsean** [Hopding/pdf-lib#408]
I installed latest version 1.4.1 and i get "Trying to parse invalid object" on react native android

i also tried react-native-pdf-lib and I still get the error. Any idea?

**Comment by Hopding** [comment]
Hello @kimsean! Can you please share the document you are trying to load?

**Comment by ivila** [comment]
@Hopding this file might work, and use copyPages to split this file will result in wrong text display.
[全本.pdf](https://github.com/Hopding/pdf-lib/files/4527797/default.pdf)

**Comment by Hopding** [comment]
@ivila I found the cause of the error you encountered and fixed it in https://github.com/Hopding/pdf-lib/pull/429.

Version [`1.5.1-rc1`](https://www.npmjs.com/package/pdf-lib/v/1.5.1-rc1) is now published. It contains the fix from #429.

You can install this new version with npm:

```
npm install pdf-lib@1.5.1-rc1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.5.1-rc1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.5.1-rc1/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.5.1-rc1/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.5.1-rc1/dist/pdf-lib.min.js

**Comment by ivila** [comment]
thank you so much.

**Comment by Hopding** [comment]
Version [`1.6.0`](https://www.npmjs.com/package/pdf-lib/v/1.6.0) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.6.0).

You can install this new version with npm:

```
npm install pdf-lib@1.6.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.6.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.6.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.0/dist/pdf-lib.min.js
