### ISSUE TITLE
Render into PDF a page containing MathJax (LaTeX for web)

### ISSUE THREAD

**Issue by josephernest** [Hopding/pdf-lib#421]
Congrats for this nice project!

Is it possible to generate PDF from a content like this (Mathjax): 

https://mathjax.github.io/MathJax-demos-web/tex-chtml.html
or 
https://mathjax.github.io/MathJax-demos-web/tex-svg.html  (SVG version)

https://github.com/mathjax/MathJax-demos-web#samples-of-mathjax-v3

I tried a few years ago with other similar JS PDF generation libraries, and it was not possible; I'm curious if it is possible with pdf-lib.

**Comment by Hopding** [comment]
Hello @josephernest!

I'm not sure I quite understand what exactly you're looking to do. If you're wanting to convert an HTML file to a PDF or embed an HTML file into a PDF document, that is not possible to do with pdf-lib. But if you can convert your MathJax expression into a PNG or JPG image, you could certainly embed it in a PDF with pdf-lib. Otherwise you'd have to figure out how to convert the MathJax expression into primitives that you can draw onto a PDF directly.

I hope this helps. Please let me know if you have any additional questions!

**Comment by josephernest** [comment]
> I'm not sure I quite understand what exactly you're looking to do. If you're wanting to convert an HTML file to a PDF or embed an HTML file into a PDF document, that is not possible to do with pdf-lib.

I was probably confusing with https://github.com/MrRio/jsPDF. 

Am I correct that your library doesn't convert HTML to PDF, but rather creates a new PDF from scratch by adding elements with `drawText(...)`?

**Comment by Hopding** [comment]
You are correct that `pdf-lib` does not support converting HTML to PDF. It supports creating new documents or modifying existing ones with the capabilities outline [here](https://github.com/Hopding/pdf-lib#features).
