### ISSUE TITLE
Multiple copyPages necessary?

### ISSUE THREAD

**Issue by alpfactory-alex** [Hopding/pdf-lib#422]
Hello,

I've wanted to copy a page from my source document and add it multiple times into my target document. However it seems that doesn't work - as soon as I add content to his newly added page all other pages are getting the same content?

Pseudo code:
```js
const newDoc = 
const sourceDoc =

const [copiedPage] = await newDoc.copyPages(sourceDoc, [0])

for (let i =0; i < 10; i += 1) {
  const newPage = newDoc.addPage(copiedPage)
  // Add some stuff to newPage here like images or text
}
```
However if I copy the page every time again within my loop it works as desired?

**Comment by Hopding** [comment]
Hello @alpfactory-alex!

This is expected behavior. It is possible to add the same page at multiple locations in the document. That being said, you can clone the page as described in https://github.com/Hopding/pdf-lib/issues/47#issuecomment-569315318 to add it multiple times with different content. This is a better approach than running `copyPages` multiple times. Note that we're tracking a feature request for cloning pages in https://github.com/Hopding/pdf-lib/issues/169.

I hope this helps. Please let me know if you have any additional questions!
