### ISSUE TITLE
Something wrong with custom font.

### ISSUE THREAD

**Issue by luneice** [Hopding/pdf-lib#430]
There may be a bug when using custom font, when using **English Font**  ```base64Pdf = await pdfDoc.saveAsBase64({ dataUri: true })``` will get base64 string, but using **Chinese Font** ```base64Pdf = await pdfDoc.saveAsBase64({ dataUri: true })``` cannot get base64 string. That causes nothing will show in ```frame``` in web page.

The example as follws:
```
const fontBytes = await fetch("https://abcdefg.oss-cn-shenzhen.aliyuncs.com/fonts/SiYuan.ttf").then(res => res.arrayBuffer());
const pdfDoc = await PDFDocument.create();
pdfDoc.registerFontkit(fontkit);
const SiYuan = await pdfDoc.embedFont(fontBytes);
const page = pdfDoc.addPage();
const text = '孙子兵法';
const textSize = 35;
page.setFont(SiYuan);
page.drawText(text, {
  x: 40,
  y: 450,
  size: textSize,
  color: rgb(0, 0.53, 0.71),
});
// It cannot get base64 
const base64Pdf = await pdfDoc.saveAsBase64({ dataUri: true }); 
```

**Comment by Hopding** [comment]
Hello @luneice!

I'm trying to reproduce your issue, but I'm unable to load the font at the URL you provided (`https://abcdefg.oss-cn-shenzhen.aliyuncs.com/fonts/SiYuan.ttf`). See the error below:

![image](https://user-images.githubusercontent.com/10351828/80769447-d5270d80-8b12-11ea-9116-344589d53b3e.png)

Can you please provide a different URL, or upload the font directly to this thread?

**Comment by luneice** [comment]
> Hello @luneice!
> 
> I'm trying to reproduce your issue, but I'm unable to load the font at the URL you provided (`https://abcdefg.oss-cn-shenzhen.aliyuncs.com/fonts/SiYuan.ttf`). See the error below:
> 
> ![image](https://user-images.githubusercontent.com/10351828/80769447-d5270d80-8b12-11ea-9116-344589d53b3e.png)
> 
> Can you please provide a different URL, or upload the font directly to this thread?

The font address is ```https://public-cdns.oss-cn-shenzhen.aliyuncs.com/fonts/SiYuan.ttf```.

**Comment by Hopding** [comment]
@luneice I tried running the script you provided with the font you specified. The issue is not that the `base64Pdf` cannot be created. It is produced without any errors. The problem is that it is too large for browsers to render. The string ends up being about 18.5 MB in size. Here's what Firefox's console shows:

![Screen Shot 2020-05-02 at 10 56 38 AM](https://user-images.githubusercontent.com/10351828/80869137-2eeb1d00-8c64-11ea-8ec5-c9be7122d150.png)

I converted your script to a Node script and wrote the resulting PDF to a file instead of a base64 string. The file was still fairly large (7 MB), but I was able to load it in standard PDF viewers (including Firefox and Chrome).

If you can reduce the size of the font you are using then you could get your script to work. I would recommend trying to subset it, if possible. `pdf-lib` has a [builtin subsetting feature](https://pdf-lib.js.org/docs/api/interfaces/embedfontoptions#optional-subset), but it does not seem to work for your font. Instead you could try hosting a subsetted version of the font. Here are a couple articles about how to create a subsetted font:
* https://michaeljherold.com/2015/05/04/creating-a-subset-font/
* https://www.afasterweb.com/2018/03/09/subsetting-fonts-with-glyphhanger/

This approach would have the added benefit of making the `fetch` request for the font complete more quickly since the subsetted font should be smaller than the original 10 MB version.

I hope this helps. Please let me know if you have any additional questions!
