### ISSUE TITLE
Cloning PDFDocument as-is

### ISSUE THREAD

**Issue by daniloarcidiacono** [Hopding/pdf-lib#436]
Hello,
I'd like to implement an undo/redo functionality in my application, which uses pdf-lib to manipulate a PDF. Every action of the user is stored as a sequence of "mutations" (Vuex), each one encapsulating the logic to modify the document appropriately.

To perform an "undo" operation, I need to:

 1) Reset the document to the initial state;
 2) Re-apply all the "mutations" (except the last one) to rebuild the previous state;

To implement the first step I just reload the PDF each time from the raw bytes, however it's too slow for an undo operation. Is there a way to make a perfect clone of a PDFDocument object, in order to use it as a master copy each time I have to rollback the state? (of course, hoping that cloning a PDFDocument would be considerably faster than parsing the raw byte array).

I know there is a closed issue similar to this one, however I need a perfect clone without any modifications, so I thought this was worth asking before trying the "standard" deep-cloning tools :)

Thanks

**Comment by Hopding** [comment]
Hello @daniloarcidiacono!

Apologies for the delayed response. No APIs exist for this currently. However, this should be possible to do in a way that's much faster than parsing the file anew. The entire state of a `PDFDocument` (more or less) is contained in its [`PDFContext`](https://github.com/Hopding/pdf-lib/blob/master/src/core/PDFContext.ts):
https://github.com/Hopding/pdf-lib/blob/193e48ff2ce07d72f8191087adcdd01aa3c48a62/src/api/PDFDocument.ts#L164-L165

So if you want to clone a `PDFDocument`, what you really need to do is clone its underlying `PDFContext`. The state of a `PDFContext` is contained almost entirely in its `indirectObjects` member: 
https://github.com/Hopding/pdf-lib/blob/193e48ff2ce07d72f8191087adcdd01aa3c48a62/src/core/PDFContext.ts#L58

Putting it all together in psuedo code, what you'd need in order to clone a `PDFDocument` is the following:
```js
const deepCloneMap = (map: Map<PDFRef, PDFObject>) => { ... }

class PDFContext {
  static clone(): PDFContext {
    const indirectObjects = deepCloneMap(this.indirectObjects)
    return new PDFContext(indirectObjects)
  }
  ...
}

class PDFDocument {
  static clone(): PDFDocument {
    const context = this.context.clone()
    return new PDFDocument(context)
  }
  ...
}
```

I hope this helps! Please let me know if you have any additional questions.

**Comment by manuschillerdev** [comment]
hey @Hopding 
Is this by any chance already implemented? I looked through the docs, but could not find the option, yet.

how would a proper implementation of `const deepCloneMap = (map: Map<PDFRef, PDFObject>) => { ... }` would have to look like?

**Comment by manuschillerdev** [comment]
@Hopding 
Could you give me a hint in the right direction how deepCloneMap could look like? 
I'd gladly work on a PR for the `.clone()` feature :)
