### ISSUE TITLE
How to logAcroFieldNames in 1.x.x ?

### ISSUE THREAD

**Issue by lucifiel0121** [Hopding/pdf-lib#438]
What is the " logAcroFieldNames " method in old version will be write in 1.x.x?
The old one seems use different API , so I cannot use ` acroField.get('T').toString()` .
In 1.x.x , that will be `undefined` value.

- old (0.x): `pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'). `
- new(1.x): `pdfDoc.catalog.lookup(PDFName.of('AcroForm'))`

*old version 
https://github.com/Hopding/pdf-lib/issues/48

```

const logAcroFieldNames = (pdfDoc) => {
  const acroFields = getAcroFields(pdfDoc);
  acroFields.forEach((acroField) => {
    console.log(
      'Field Name:',
      acroField.get('T').toString(),
      'Field Type:',
      acroField.get('FT').toString()
    );
  });
};

```
```

const getAcroFields = (pdfDoc) => {
  if (!pdfDoc.catalog.getMaybe('AcroForm')) return [];
  const acroForm = pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'));

  if (!acroForm.getMaybe('Fields')) return [];
  const acroFields = pdfDoc.index.lookup(acroForm.get('Fields'));

  return acroFields.array.map(pdfDoc.index.lookup);
};

```

*new one

```
const getAcroFields = pdfDoc => {
  const acroForm = getAcroForm(pdfDoc);
  if (!acroForm) return [];

  const fieldRefs = acroForm.lookupMaybe(PDFName.of('Fields'), PDFArray);
  if (!fieldRefs) return [];

  const fields = new Array(fieldRefs.size());
  for (let idx = 0, len = fieldRefs.size(); idx < len; idx++) {
    fields[idx] = fieldRefs.lookup(idx);
  }
  return fields;
};
```

**Comment by lucifiel0121** [comment]
I check for sample code to get this and works.


```
const logAcroFieldNames = (pdfDoc) => {
  const acroFields = getAcroFields(pdfDoc);
  acroFields.forEach((acroField) => {
    console.log(
      'Field Name:',
      acroField.get(PDFName.of('T')),
      'Field Type:',
      acroField.get(PDFName.of('FT'))
    );
  });
};

```

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFForm.getFields`](https://pdf-lib.js.org/docs/api/classes/pdfform#getfields) method is of particular relevance to this issue.
