### ISSUE TITLE
Change Fill Color to Transparent

### ISSUE THREAD

**Issue by MomTo3Girls3Boys** [Hopding/pdf-lib#446]
I’m working on a tool that will let people add a background image to each page of their PDF.  I’m using PDF-LIB to create a new PDF, add a new page, put the image on that page, then copy the correspond page from the source PDF onto that page - then repeat for each page in the source PDF.  It works great as long as the PDF they upload is transparent. If the PDF has was created with PowerPoint or Keynote, it has a white background and thus the image doesn’t show though when you put it behind each page of the PDF.  Is there a way to modify the white background fill color in the source PDF with PDF-LIB so that when I copy it into the new PDF it is now transparent?

**Comment by MomTo3Girls3Boys** [comment]
Here's a sample file with a white background.
[2020monthly_journal.pdf](https://github.com/Hopding/pdf-lib/files/4637385/2020monthly_journal.pdf)

**Comment by Hopding** [comment]
Hello @MomTo3Girls3Boys!

This is certainly possible to do. Although it's a bit tricky. There are no high level APIs for this right now, so it requires you to dig into the page's content streams and manipulate them yourself. 

Page contents stream are basically strings containing a sequence of operators and their arguments. These operators tell PDF readers exactly how to render the page. We can remove the background color of a page if we can identify the operators used to draw the background and remove them from the content stream.

I've written an example script showing one way to do this for the PDF you shared. It removes the background from the first page of the PDF and copies the modified page into a new document. See below:

```js
import fs from 'fs';
import {
  PDFDocument,
  PDFRawStream,
  decodePDFRawStream,
  arrayAsString,
  PDFRef,
  rgb,
  PDFObject,
  PDFPage,
} from 'pdf-lib';

const pink = rgb(255 / 255, 128 / 255, 191 / 255);

const whitespace = '[\\0\\t\\n\\f\\r\\ ]+';
const forwardSlash = '\\/';
const alphanumerics = '\\w+';
const decimal = '\\d+\\.\\d+|\\d+';

// prettier-ignore
const whiteBackgroundOperatorsRegex = new RegExp(
  `${forwardSlash}${alphanumerics}${whitespace}cs${whitespace}` +
  `1${whitespace}1${whitespace}1${whitespace}sc${whitespace}` +
  `(?<x1>${decimal})${whitespace}(?<y1>${decimal})${whitespace}m${whitespace}` +
  `(?<x2>${decimal})${whitespace}(?<y2>${decimal})${whitespace}l${whitespace}` +
  `(?<x3>${decimal})${whitespace}(?<y3>${decimal})${whitespace}l${whitespace}` +
  `(?<x4>${decimal})${whitespace}(?<y4>${decimal})${whitespace}l${whitespace}` +
  `h${whitespace}` +
  `f`
);

const almostEqual = (a: string | number, b: string | number, error = 0.1) =>
  Math.abs(Number(a) - Number(b)) <= error;

const tryToDecodeStream = (maybeStream?: PDFObject) => {
  if (maybeStream instanceof PDFRawStream) {
    return arrayAsString(decodePDFRawStream(maybeStream).decode());
  }
  return undefined;
};

const removeWhiteBackground = (
  streamContents: string,
  size: { width: number; height: number },
) => {
  let match = streamContents.match(rgx);
  while (match) {
    const { x1, y1, x2, y2, x3, y3, x4, y4 } = match.groups || {};
    const matchSizeIsWithinSize =
      almostEqual(x1, 0) &&
      almostEqual(y1, size.height, 5) &&
      almostEqual(x2, size.width, 5) &&
      almostEqual(y2, size.height, 5) &&
      almostEqual(x3, size.width, 5) &&
      almostEqual(y3, 0) &&
      almostEqual(x4, 0) &&
      almostEqual(y4, 0);
    if (!matchSizeIsWithinSize) break;
    const targetStart = match.index || 0;
    const targetEnd = targetStart + match[0].length;
    streamContents =
      streamContents.substring(0, targetStart) +
      streamContents.substring(targetEnd, streamContents.length);
    match = streamContents.match(rgx);
  }
  return streamContents;
};

const removePageBackground = (page: PDFPage) => {
  const { Contents } = page.node.normalizedEntries();
  if (!Contents) return;
  Contents.asArray().forEach((streamRef) => {
    if (streamRef instanceof PDFRef) {
      const stream = page.doc.context.lookup(streamRef);
      const contents = tryToDecodeStream(stream);
      if (contents) {
        const newContents = removeWhiteBackground(contents, page.getSize());
        const newStream = page.doc.context.flateStream(newContents);
        page.doc.context.assign(streamRef, newStream);
      }
    }
  });
};

(async () => {
  const pdfDoc = await PDFDocument.load(
    fs.readFileSync('/Users/user/Desktop/2020monthly_journal.pdf'),
  );

  const page = pdfDoc.getPage(0);
  removePageBackground(page);

  const newDoc = await PDFDocument.create();
  const embeddedPage = await newDoc.embedPage(page);

  const newPage = newDoc.addPage([page.getWidth(), page.getHeight()]);
  newPage.drawRectangle({
    color: pink,
    width: page.getWidth(),
    height: page.getHeight(),
  });
  newPage.drawPage(embeddedPage);

  const pdfBytes = await newDoc.save();

  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```

This outputs the following page:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/82105640-f75b8680-96e1-11ea-9f7b-4e9c2b9bb499.png" height="500">
</kbd>

>

Here's an excerpt of the beginning of the page's content stream (reformatted so each line contains one operator for readability):
```
q 
Q 
q 
0 0.00001448393 431.76 648 re 
W 
n 
/Cs1 cs 
1 1 1 sc 
0 648 m 
431.76 648 l 
431.76 0.00001448393 l 
0 0.00001448393 l 
h 
f 
Q 
q 
/Cs1 cs 
1 1 1 sc 
0 648 m 
432 648 l 
432 0.00001689792 l 
0 0.00001689792 l 
h 
f 
0 0 0 sc 
q 
0.24 0 0 0.24 171.55 -68.63998 cm 
BT 
-0.0013 Tc 
183.3333 0 0 183.3333 0 2700 Tm 
/TT2 1 Tf 
(!"!") Tj 
ET 
Q 
q 
```

The script constructs a regex that looks like the following (newlines added for readability):
```js
/\/\w+[\0\t\n\f\r\ ]+cs[\0\t\n\f\r\ ]+
1[\0\t\n\f\r\ ]+1[\0\t\n\f\r\ ]+1[\0\t\n\f\r\ ]+sc[\0\t\n\f\r\ ]+
(?<x1>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+(?<y1>\d+\.\d+|\d+[\0\t\n\f\r\ ]+m[\0\t\n\f\r\ ]+
(?<x2>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+(?<y2>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+l[\0\t\n\f\r\ ]+
(?<x3>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+(?<y3>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+l[\0\t\n\f\r\ ]+
(?<x4>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+(?<y4>\d+\.\d+|\d+)[\0\t\n\f\r\ ]+l[\0\t\n\f\r\ ]+
h[\0\t\n\f\r\ ]+
f/
```

This causes it to match sequences of operators that draw a white background, such as the following:
```
/Cs1 cs 
1 1 1 sc 
0 648 m 
431.76 648 l 
431.76 0.00001448393 l 
0 0.00001448393 l 
h 
f 
```

As it turns out, the PDF you shared contains multiple of these blocks (with slightly different x/y positions), so the script repeatedly matches and removes them until no more matches are found.

Finally, it's important to note that the script I shared is not bullet proof. It isn't guaranteed to remove any background color from any possible input PDF. Right now the regex is only checking for white backgrounds drawn in the RGB colorspace with the `sc` and `cs` operators. Also, after matching the colorspace operators, it is assuming a rectangle is drawn using the following sequence of operators: `m`, `l`, `l`, `l`, `h`, `f`. This is just one of many ways a rectangle can be drawn to a page's content stream (see **Annex A - Operator Summary** of the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) to understand what other ways a rectangle can be drawn).

I hope this helps. Please let me know if you have any additional questions!

**Comment by cozykitten** [comment]
@MomTo3Girls3Boys How do you copy an exsting page _onto_ another existing page?
If I use copyPages + insert, it will just insert the page before my target page, but not on top of it?

I'm trying to create a dark mode version of an existing pdf, so far this worked for text by drawing a white rect on top with blendMode: Difference, but I don't want to draw that on top of images, since that would invert them.
So I want to create a new page, draw a black rect, then copy the existing page with the image on top.

The 2 problems are I can't figure out how to copy a page ontop of another page and secondly,.. how to even find out whether a page has an image or just text.
