### ISSUE TITLE
Text highlight not possible

### ISSUE THREAD

**Issue by vladimarius** [Hopding/pdf-lib#449]
Hi,
I couldn't find any api functions which could be used to highlight text in PDF document. By "highlighting" I mean drawing colored rectangle behind a text, not on top of it.

Is this possible ?
Please point me to the right direction please.

**Comment by vegarringdal** [comment]
This would have been super useful
Search text and highlight text.

**Comment by Hopding** [comment]
Hello @vladimarius! 

This is technically possible to do. But I'm afraid it would take some work to implement. It would require the ability to inject graphics operators into arbitrary positions of an existing content stream (the current `PDFPage` APIs only allow appending to the end of a content stream). In order for this to be feasible, it would be necessary to parse existing content streams. Designing such an API in a generic way would also require some form of parsing on the content stream so that you could figure out where, exactly, to insert the new operators within the stream.

Given all that, I do not think this feature will land in pdf-lib anytime soon. That is, unless somebody wants to work on it and create a PR. I'd be happy to answer questions if anybody is interested.
