### ISSUE TITLE
Why does this take 6GB of RAM to process 200 pages? (How to free memory after processing a few pages)

### ISSUE THREAD

**Issue by josephernest** [Hopding/pdf-lib#470]
The following code takes an input PDF of 200 pages (~ 10 MB), duplicate each page, crop the first duplicate to size (100, 100) and crop the second duplicate to size (200, 200).  (In my real code, it does other things too, such as rotate, change the margins, etc. but it's off topic here).

Strangely, it crashes Chrome by using 6 GB of RAM. 

**How to do it by using less RAM?**

```
<html>
<head>
<script src="https://unpkg.com/pdf-lib"></script>
<script src="https://unpkg.com/downloadjs"></script>
</head>
<body>
<input type="file" id="file">
</body>
<script>
const { degrees, PDFDocument } = PDFLib;
var typedarray = null;
async function modifyPdf() {
    const pdfDoc = await PDFDocument.load(typedarray);
    const pdfDoc2 = await PDFDocument.create();
    const pages = pdfDoc.getPages()
    for (var i = 0; i < pages.length; i++) {
        console.log(i);
        const [p1] = await pdfDoc2.copyPages(pdfDoc, [i])
        const [p2] = await pdfDoc2.copyPages(pdfDoc, [i])
        p1.setSize(100, 100);
        p1.setRotation(degrees(270));
        p2.setSize(200, 200);
        p2.setRotation(degrees(270));
        pdfDoc2.addPage(p1);
        pdfDoc2.addPage(p2);
    }
    const pdfBytes = await pdfDoc2.save()
    download(pdfBytes, 'out.pdf', "application/pdf");
}
document.getElementById('file').onchange = function(event) {
    var file = event.target.files[0];
    var fileReader = new FileReader();  
    fileReader.onload = function() {
        typedarray = new Uint8Array(this.result);
        modifyPdf();
    };
    fileReader.readAsArrayBuffer(file);
}
</script>
</html>
```

**Comment by Hopding** [comment]
Hello @josephernest!

The reason your script is using so much RAM is because of how it is copying pages. Copying pages between documents is a relatively expensive operation (especially if you're dealing with large documents or pages with a lot of media on them). As such, you want to minimize the number of times you call [`PDFDocument.copyPages`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#copypages). You should figure out the indices of all the pages you want to copy at any point in your script and pass them as an array to copy everything in one-shot. 

I've updated your script to perform a one-shot copy as described above (I also use the `copyPage` function from https://github.com/Hopding/pdf-lib/issues/47#issuecomment-569315318):

```html
<html>
  <head>
    <script src="https://unpkg.com/pdf-lib"></script>
    <script src="https://unpkg.com/downloadjs"></script>
  </head>
  <body>
    <input type="file" id="file" />
  </body>
  <script>
    const { degrees, PDFDocument, PDFName, PDFPage } = PDFLib;

    document.getElementById('file').onchange = function (event) {
      var file = event.target.files[0];
      var fileReader = new FileReader();
      fileReader.onload = function () {
        modifyPdf(this.result);
      };
      fileReader.readAsArrayBuffer(file);
    };

    async function modifyPdf(inputPdfBytes) {
      const inputPdf = await PDFDocument.load(inputPdfBytes);
      const outputPdf = await PDFDocument.create();

      const copiedPages = await outputPdf.copyPages(
        inputPdf,
        inputPdf.getPageIndices(),
      );

      copiedPages.forEach((page1) => {
        const page2 = copyPage(page1);
        page1.setSize(100, 100);
        page1.setRotation(degrees(270));
        page2.setSize(200, 200);
        page2.setRotation(degrees(270));
        outputPdf.addPage(page1);
        outputPdf.addPage(page2);
      });

      const pdfBytes = await outputPdf.save();
      download(pdfBytes, 'out.pdf', 'application/pdf');
    }

    /* Copies a PDFPage object (from https://github.com/Hopding/pdf-lib/issues/47#issuecomment-569315318) */
    const copyPage = (originalPage) => {
      const cloneNode = originalPage.node.clone();

      const { Contents } = originalPage.node.normalizedEntries();
      if (Contents) cloneNode.set(PDFName.of('Contents'), Contents.clone());

      const cloneRef = originalPage.doc.context.register(cloneNode);
      const clonePage = PDFPage.of(cloneNode, cloneRef, originalPage.doc);
      return clonePage;
    };
  </script>
</html>
```

The reason calling `PDFDocument.copyPages` once with all the page indices uses less memory than calling it with one index multiple times is because of shared object references. When you copy a page into another document, `pdf-lib` has to do a recursive traversal of the page and all the objects it references behind the scenes. As a result, copying a single page often means copying hundreds of objects under the hood. Quite often, pages within a document share objects to reduce file size. Embedded fonts are great example of this. A font need only be embedded once, but can be referenced by hundreds of pages.

Suppose you want to copy 5 pages from a document that all use the same embedded font. If you do this in one-shot, then `pdf-lib` can figure out that the 5 pages you're copying are all referencing the same font objects and will only copy them once. But if you call `PDFDocument.copyPages` once for each page, then the font will be copied 5 times. This greatly increases the size of the resulting document. **For this reason, calling `PDFDocument.copyPages` inside a loop is an anti-pattern.**

I hope this helps. Please let me know if you have any additional questions!

**Comment by josephernest** [comment]
Thank you @Hopding for your great and detailed answer! 

Massive improvement indeed from 6 GB to less than ... 100 MB I think :)

All the best for the pdf-lib project!

**Comment by josephernest** [comment]
@Hopding Also, when doing `const outputPdf = await PDFDocument.create();`, is there a way to copy the PDF metadata (author, title, etc.) from the variable `inputPdf`?
Thanks again.

**Comment by wdelmas** [comment]
pdf-lib loads entire documents into memory with no streaming support. For your scenario consuming 6GB+:

**Why it happens:** Each page copies font subsets, embedded images get duplicated rather than referenced. The library wasn't designed for batch processing.

**Workarounds:**

1. **Process in batches** — Create 20 small PDFs, merge at the end
2. **Force GC** — Set references to `null`, call `global.gc()` if running Node with `--expose-gc`
3. **Worker threads** — Spawn separate processes that die after each batch (memory gets freed with process)

For high-volume scenarios, consider whether you need pdf-lib at all. If you're generating from HTML, a headless browser or API service handles memory management for you.
