### ISSUE TITLE
[BUG] embedding image with alpha channel broken

### ISSUE THREAD

**Issue by AmilKey** [Hopding/pdf-lib#473]
Hello everyone, I use embedding images with transparency to my document, but this function was broken in version 1.3.1, I have attached examples of generated documents in different versions.

example embedding
https://jsfiddle.net/d1uLne7g/

looks like that was broken into version 1.3.2
https://github.com/Hopding/pdf-lib/compare/v1.3.1..v1.3.2#diff-4f449742b7e9f5f136fe91da08ad248d

attached 2 pdf generated in version 1.3.1 and 1.7.0
[1.3.1.pdf](https://github.com/Hopding/pdf-lib/files/4736755/1.3.1.pdf)
[1.7.0.pdf](https://github.com/Hopding/pdf-lib/files/4736756/1.7.0.pdf)

@Hopding

**Comment by Hopding** [comment]
Version [`1.9.0`](https://www.npmjs.com/package/pdf-lib/v/1.9.0) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.9.0).

You can install this new version with npm:

```
npm install pdf-lib@1.9.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.min.js
