### ISSUE TITLE
Semi-transparent PNG rendered opaque in PDF

### ISSUE THREAD

**Issue by sbastias** [Hopding/pdf-lib#483]
Im trying to watermark a PDF with a semi-transparent PNG, but the semi-transparent portions are being rendered fully opaque in resulting PDF.

I can't find anything in the docs regarding transparency... any help would be greatly appreciated.

**Comment by soadzoor** [comment]
I noticed the same thing, although, not with all PNGs. Strange.

**Comment by sbastias** [comment]
@soadzoor, Where/how are you defining fillStyle and fillRect?
Neither of these appear in the API documentation....

**Comment by soadzoor** [comment]
@sbastias I'm using the built-in canvas context for those: https://www.w3schools.com/tags/canvas_fillrect.asp

**Comment by sbastias** [comment]
@soadzoor How is that useable with pdf-lib?

**Comment by soadzoor** [comment]
@sbastias It's not really related to pdf-lib. You can use canvas context for a lot of useful things, image manipulation mostly. So I'm simply generating the raster image from the svg using that.

**Comment by sbastias** [comment]
I'm using pdf-lib server side, node, so I don't have access to the HTML5 Canvas...

**Comment by soadzoor** [comment]
@sbastias I think you can use https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas if you really want, but it's not mandatory to this particular issue

**Comment by sbastias** [comment]
Checking in to keep this issue alive.... I think there are lots of semi-transparent PNG uses....

**Comment by Hopding** [comment]
Hello @sbastias!

I'm aware of this issue and will get around to investigating and fixing it as soon as possible. But I have a number of irons in the fire right now, so I can't look into this just yet.

If anybody would like to help troubleshoot this issue, the code for PNG embedding can be found in these two files:
* https://github.com/Hopding/pdf-lib/blob/master/src/core/embedders/PngEmbedder.ts
* https://github.com/Hopding/pdf-lib/blob/master/src/utils/png.ts

It would be especially useful to know if the alpha channel is being split correctly for images that are losing their transparency:

https://github.com/Hopding/pdf-lib/blob/556c73c3c05c8b05cc27e59d779f6fb76166aa6d/src/utils/png.ts#L57

Also, just want to note that this issue is related to https://github.com/Hopding/pdf-lib/issues/473.

**Comment by soadzoor** [comment]
@Hopding , @sbastias Good news!

I've found the issue. It was in this line:
```
const hasAlphaValues = alphaChannel.some((a) => a < 1);
```

Since the alpha values are stored in a `Uint8Array` here, the range goes between 0 and 255, and not between 0 and 1 as that line assumes. So, it only worked with png images that has at least one pixel that is fully transparent (0 alpha). My workaround (`ctx.translate(0, 1)`) worked, because it "added" a completely transparent line to the top of the image.

Anyway, I've changed that line to this:
```
const hasAlphaValues = alphaChannel.some((a) => a < 255);
```

and it solved the issue. Tested with my pacman pngs above.

So, the ball is in @Hopding 's court now, to review/accept the PR with the fix. 🚀 

Cheers

**Comment by Hopding** [comment]
Version [`1.9.0`](https://www.npmjs.com/package/pdf-lib/v/1.9.0) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.9.0).

You can install this new version with npm:

```
npm install pdf-lib@1.9.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.min.js

**Comment by sbastias** [comment]
Hey guys, amazingly quick work. I was going to try to figure it out, not
sure I could have.... But impressively fast solution!
