### ISSUE TITLE
custom font  font subset with Chinese font does not work properly

### ISSUE THREAD

**Issue by rawbin-** [Hopding/pdf-lib#494]
ref for https://github.com/Hopding/pdf-lib/issues/207
and example for https://github.com/Hopding/pdf-lib/issues/430

using the subset option to reduce the generated pdf size, when use subset, the pdf content is not expected

use  https://github.com/rawbin-/node-pdf-test  to reproduce this issue
`with-pdflib.js` and `with-pdflib-issue-430.js`

expected
![image](https://user-images.githubusercontent.com/8169783/84870410-e1126300-b0b1-11ea-8dc0-7597b41cb274.png)

but got
![image](https://user-images.githubusercontent.com/8169783/84870470-f1c2d900-b0b1-11ea-83a0-83852f89f156.png)

or even blank with  `issue-430` example

**Comment by rawbin-** [comment]
this example will show https://github.com/rawbin-/node-pdf-test/blob/master/pdflib-test.js
when custom font use subset ,the original english font also affected

just change the following to see the difference
```
    // this line works well
//     const customFont = await pdfDoc.embedFont(fontBytes)

    // this does not work properly
    const customFont = await pdfDoc.embedFont(fontBytes,{subset:true})
```


```
const fs = require('fs')
const { PDFDocument, rgb } = require('pdf-lib')
const fontkit = require('@pdf-lib/fontkit')

async function generatePDF(){
    // This should be a Uint8Array or ArrayBuffer
// This data can be obtained in a number of different ways
// If you're running in a Node environment, you could use fs.readFile()
// In the browser, you could make a fetch() call and use res.arrayBuffer()
    const fontBytes = fs.readFileSync('./font/pingfang.ttf')

// Create a new PDFDocument
    const pdfDoc = await PDFDocument.create()

// Register the `fontkit` instance
    pdfDoc.registerFontkit(fontkit)

// Embed our custom font in the document
    // this line works well
//     const customFont = await pdfDoc.embedFont(fontBytes)

    // this does not work properly
    const customFont = await pdfDoc.embedFont(fontBytes,{subset:true})


// Add a blank page to the document
    const page = pdfDoc.addPage()

// Create a string of text and measure its width and height in our custom font
    const text = '中文字体你行不行This is text in an embedded font!'
    const textSize = 35
    const textWidth = customFont.widthOfTextAtSize(text, textSize)
    const textHeight = customFont.heightAtSize(textSize)

// Draw the string of text on the page
    page.drawText(text, {
        x: 40,
        y: 450,
        size: textSize,
        font: customFont,
        color: rgb(0, 0.53, 0.71),
    })

// Draw a box around the string of text
    page.drawRectangle({
        x: 40,
        y: 450,
        width: textWidth,
        height: textHeight,
        borderColor: rgb(1, 0, 0),
        borderWidth: 1.5,
    })

// Serialize the PDFDocument to bytes (a Uint8Array)
    const pdfBytes = await pdfDoc.save()
    fs.writeFileSync('./dist/pdflib-test.pdf',pdfBytes)

// For example, `pdfBytes` can be:
//   • Written to a file in Node
//   • Downloaded from the browser
//   • Rendered in an <iframe>
}

generatePDF()

```

**Comment by Hopding** [comment]
Hello @rawbin-! 

As you have noticed, font subsetting unfortunately does not work with all types of fonts. The library `pdf-lib` uses for custom embedding and subsetting is `@pdf-lib/fontkit`, which is a fork of [`fontkit`](https://github.com/foliojs/fontkit). I've noticed issues myself when attempting to subset certain fonts. I haven't had time to track it down, which is why subsetting is not the default behavior for `pdf-lib`. 

As best I can tell, the issue exists upstream in [`fontkit`](https://github.com/foliojs/fontkit). If so, there's nothing that can be done to `pdf-lib` directly to fix it. So it would be best to open an issue on that repo. If/when it gets fixed, it can be pulled into `@pdf-lib/fontkit` (and, therefore, `pdf-lib`). 

One way you could attempt to verify that the issue exists in [`fontkit`](https://github.com/foliojs/fontkit) is by trying to embed and subset the font with [`pdfkit`](https://github.com/foliojs/pdfkit). `pdfkit` also uses `fontkit` internally, so if you can reproduce the issue that way, it's highly likely to be a bug in `fontkit`.

**Comment by Hopding** [comment]
I'm going to close this issue for now. It only manifests when users choose to subset a font and does not appear to be an issue with pdf-lib specifically. It is also unlikely to be fixed in the near future unless an enterprising individual decides to work on it.

**Comment by znacloud** [comment]
I published a new package renamed to [pdf-fontkit](https://www.npmjs.com/package/pdf-fontkit) to fix the subsetting issues. I've tested it and it works fine. Maybe you can use this package to replace @pdf-lib/fontkit.

**Comment by Betree** [comment]
@znacloud Thanks for sharing your solution, it works like a charm! It would be great to get this integrated into the main project.
