### ISSUE TITLE
Open parenthesis

### ISSUE THREAD

**Issue by jumpypixels** [Hopding/pdf-lib#505]
When these is a single left or right parenthesis in a string, everything from the open parenthesis won't display
for example: 
text: 1) ad cdefg @#$$%^%&^%^&**{}()[]
output : 1

If I have a pair of left and right parenthesis , the string will display correctly like:
(1)ad cdefg @#$$%^%&^%^&**{}()[]

The code segment is:
        acroField.delete(PDFName.of('AP'));
        // acroField.set(PDFName.of('AP'), PDFString.of(text));
        acroField.set(PDFName.of('V'), PDFString.of(text));
        acroField.set(PDFName.of('Ff'), PDFNumber.of(
            1 << 0 // Read Only
            |
            1 << 12 // Multiline
        ));

Did I do anything wrong?

**Comment by daniloarcidiacono** [comment]
Hello,
I'm not the author of this library, but I think this is a bug of `PDFString `class. Its documentation reports:

```
  // The PDF spec allows newlines and parens to appear directly within a literal
  // string. These character _may_ be escaped. But they do not _have_ to be. So
  // for simplicity, we will not bother escaping them.
```

which is wrong, because parenthesis may not be escaped **only** if they are balanced.

Another problem is that strings longer than 255 characters are split into multiple lines, however this is not handled by PDFString.

![image](https://user-images.githubusercontent.com/17272323/86236586-9d802480-bb9a-11ea-9dcf-3127a2b56faf.png)

The image shows a PDF form field with /TU set to a string 320 characters long. Adobe Reader automatically inserts a 5C0D (a reverse solidus followed by carriage return) at the 255th character. PDFString does not handle this.

**Comment by jumpypixels** [comment]
Thanks. You pointed to the right direction. I added to double escape \\) and it solved the problem

**Comment by daniloarcidiacono** [comment]
Glad to be of help. Anyway, could you please leave this bug opened? This is a bug in `PDFString` that should be addressed.
