### ISSUE TITLE
High ram and cpu usage crash our node server

### ISSUE THREAD

**Issue by windgaucho** [Hopding/pdf-lib#507]
Hello, we are using pdf-lib for modify pdf files that the users are uploading into our system.
The user upload a pdf in a "temporal" minio bucket, lather retrieve the pdf file from minio and stamp a image and a date and hour in every page of the pdf. Later save the new pdf in another minio bucket.
All works ok, but when the app is intensity used, the server is crashing because de high ram and cpu usage.

Here is the code that we are using to stamp a pdf:

````
async stampPdf(docAct, bucket, signer) {
  const userPrivate = new User();

  return this.getBufferObject(bucket.toLowerCase(), `${docAct.archivoId}`)
    .then(async (buffer) => {
      try {
        const pdfParser = new PDFParser();
        pdfParser.parseBuffer(buffer);
      } catch (e) {
        console.error(`
          ${e}
        `);

        return e;
      }
      const pdfDoc = await PDF.load(buffer);
      const imageStamp = Buffer.from(imageStamp64, 'base64');
      const embedImageStamp = await pdfDoc.embedPng(imageStamp);
      const imageStampDims = embedImageStamp.scale(0.25);
      const pages = pdfDoc.getPages();

      const creationDate = moment(docAct.creationDate).format('DD/MM/YYYY');
      const stampDate = moment(docAct.stampDate).format('DD/MM/YYYY');

      let signerName = 'System';

      if (signer !== 'System') {
        const usuario = await userPrivate.get(signer);
        signerName = usuario.apyn;
      }

      pages.forEach((page) => {
        const fontSize = 9;
        const texto = `Creation Date: ${creationDate} | Stamp Date: ${stampDate} | Signer ${signerName}`;
        page.drawText(texto, {
          x: 15,
          y: 75 + 6 * fontSize,
          size: fontSize,
          color: rgb(0, 0, 0),
          rotate: degrees(90),
        });

        page.drawImage(embedImageStamp, {
          x: imageStampDims.width / 2,
          y: page.getHeight() - imageStampDims.height - 50,
          width: imageStampDims.width,
          height: imageStampDims.height,
          rotate: degrees(23 - (Math.random() * 11 - 5)),
        });
      });
      const pdfBytes = await pdfDoc.save();
      return Buffer.from(pdfBytes);
    })
    .catch((e) => {
      console.error(`
      ${e}
      `);
      return e;
    });
}

async getBufferObject(bucket, archivoId) {
  return new Promise((resolve, reject) => {
    const file = [];
    minioClient.getObject(bucket.toLowerCase(), archivoId, (err, data) => {
      if (err) reject(err);
      if (data) {
        data.on('data', (chunk) => {
          file.push(chunk);
        });
        data.on('end', () => {
          return resolve(Buffer.concat(file));
        });
        data.on('error', (errData) => {
          return reject(new Error(errData));
        });
      }
    });
  });
}
````
Can anybody tell me if this is the correct way to stamp a pdf file using pdf-lib?

**Comment by soadzoor** [comment]
@windgaucho Have you considered moving this functionality to the client instead of the server? Meaning it would run on the client's browser, in javascript, so it would lift off a heavy weight from your server, especially when there are lots of users using your application simultaneously.

**Comment by Hopding** [comment]
Hello @windgaucho! 

Your pdf-lib code looks mostly fine. If you're having memory issues, it's likely due to the number of PDFs your system has in-memory at once. pdf-lib currently loads the whole input PDF into memory when it's being processed, which can be inefficient in high-load systems. See https://github.com/Hopding/pdf-lib/issues/121, https://github.com/Hopding/pdf-lib/issues/197, and https://github.com/Hopding/pdf-lib/issues/239.

That being said, your code is doing unnecessary extra work here:
```js
const pdfParser = new PDFParser(); 
pdfParser.parseBuffer(buffer);
```
This parsing is already done internally by `PDFDocument.load`. If you're worried about parsing errors, I'd suggest wrapping `PDFDocument.load` with a try/catch, rather than calling the parser yourself.

It's also worth noting that images can take up a substantial amount of memory (often more than the PDF files themselves). So if your `imageStamp64` is too large, that might actually the the primary cause if your memory issues.

**Comment by wdelmas** [comment]
pdf-lib loads entire documents into memory with no streaming support. For your scenario consuming 6GB+:

**Why it happens:** Each page copies font subsets, embedded images get duplicated rather than referenced. The library wasn't designed for batch processing.

**Workarounds:**

1. **Process in batches** — Create 20 small PDFs, merge at the end
2. **Force GC** — Set references to `null`, call `global.gc()` if running Node with `--expose-gc`
3. **Worker threads** — Spawn separate processes that die after each batch (memory gets freed with process)

For high-volume scenarios, consider whether you need pdf-lib at all. If you're generating from HTML, a headless browser or API service handles memory management for you.
