### ISSUE TITLE
Removing unused fonts

### ISSUE THREAD

**Issue by ztoben** [Hopding/pdf-lib#540]
I'm wondering if there is a way to use this library in a way that it would know which fonts are being used in a pdf and un-embed the ones that are not in use. Thanks!

**Comment by Hopding** [comment]
Hello @ztoben!

pdf-lib does not provide any special APIs to do something like this. However, it does provide the low-level access that you would need in order to implement it yourself. Doing so would require some understanding of the PDF specification, but it certainly could be done. Just wouldn't be the easiest thing to do if you aren't already familiar with the spec and don't want to get your hands dirty.
