### ISSUE TITLE
CANVAS-like API requirement

### ISSUE THREAD

**Issue by hdwong** [Hopding/pdf-lib#544]
pdf-lib is the best pdf library in javascript I have ever seen.

In my project, the end-user draw some content in HTML CANVAS on the browser then save to pdf, and finally uses for printing.

The problem is that pdf-lib and CANVAS have different coordinate systems and the orientation of the x axes, CANVAS is top-left system. In addition, can we add some canvas-like API (or a proxy module) to pdf-lib?

Thanks again for developing a great library!

**Comment by jotae1e** [comment]
Is your project public?

**Comment by hdwong** [comment]
> Is your project public?

No, this is a project of out company.

**Comment by Hopding** [comment]
Hello @hdwong! I can certainly see how a canvas-like API would be useful. However, that would best be done in a wrapper library, rather than pdf-lib itself. It shouldn't be too hard to create either. However, I do not personally have time to develop something like this. But if anybody attempts to create such a library and has questions, I'd be happy to answer them!

**Comment by hdwong** [comment]
Thanks @Hopding

**Comment by oren-l** [comment]
@hdwong I'm currently working on a pdf editor with pdfjs and this library, if this is still relevant let me know if I can help.

**Comment by Lex-talionis** [comment]
Hi guys, I have been trying to do this recently and making small steps but getting there. But I noticed this library the other day based off this library. 

https://labelmake.jp/javascript-pdf-generator-library/template-design/

Seems to be what your looking for.
