### ISSUE TITLE
Tree-shaking standard fonts possible?

### ISSUE THREAD

**Issue by manniL** [Hopding/pdf-lib#566]
Hey all 👋🏻

I'm wondering if there is a way to tree-shake the "standard fonts" as they are a huge portion of the bundle chunk containing `pdf-lib`.

<img width="762" alt="Webpack analyze" src="https://user-images.githubusercontent.com/640208/90335460-7ad48e80-dfd5-11ea-9db4-dda130b3f197.png">

Even when "only" using `PDFDocument, the fonts are included in the bundle.

---

## Reproduction

1. Create a new folder and add a `test.js` file with the following content`

```js
import PDFDocument  from 'pdf-lib'

async function foo () {
      const newPdf = await PDFDocument.create()
}

foo()
```

This ensures that we "only" create an empty PDF Document, nothing else.

2. Add webpack, babel and the lib as dependencies: `yarn add pdf-lib webpack webpack-cli babel-loader @babel/core`
3. Run `webpack ./test.js -o bundle.js -p --display-chunks --display-modules --display-origins --module-bind js=babel-loader`

## Expected

Having a small result chunk without the StandardFonts.

## Actual

A 344 KiB Bundle.

<img width="750" alt="Webpack result" src="https://user-images.githubusercontent.com/640208/90335592-3f868f80-dfd6-11ea-9cd8-e6e90b7dc661.png">

Related issues: #82

**Comment by Hopding** [comment]
Hello @manniL! It is not currently possible to tree-shake the standard fonts. This is an issue I would like to fix, as the standard fonts occupy a huge amount of the bundle size. This is annoying if you don't use them. But it also impacts users that do use them, because most of the time only one or two of the fonts are used. Rarely all 14 of them!

That being said, I'm not sure if this can be fixed without a breaking API change. I think an API like this would solve the problem quite nicely:
```js
import { PDFDocument, HelveticaFont } from 'pdf-lib';

const pdfDoc = await PDFDocument.create();
const helvetica = await pdfDoc.embedFont(HelveticaFont);
```
or this

```js
import { PDFDocument } from 'pdf-lib';
import { Helvetica } from '@pdf-lib/standard-fonts';

const pdfDoc = await PDFDocument.create();
const helvetica = await pdfDoc.embedFont(Helvetica);
```
At first glance, I don't see a way to do achieve either of these APIs without a breaking change. It might be possible, though. If anybody would like to investigate this further, I'd be happy to accept a PR for it (again, assuming it can be done without breaking changes). 

If, in fact, breaking changes are necessary, then fixing this will have to wait for `pdf-lib@2.0`. There are several breaking features I'd like to include in 2.0, but don't currently have a roadmap for this.

**Comment by Hopding** [comment]
I should also mention that `StandardFonts.Helvetica` is used internally by `pdf-lib`. This is why you can draw text and fill forms without specifying a font explicitly. I don't think it would be possible to tree-shake this. And I think the user experience would suffer significantly from being forced to always specify a font. So even once the API is reworked to allow tree-shaking of the standard fonts, it may not ever be possible to tree-shake `StandardFonts.Helvetica`. But even so, getting rid of the other 13 fonts would still reduce the bundle size significantly.

**Comment by manniL** [comment]
Hey @Hopding! Thanks for the detailed answer 🙏 

I see the point there, definitely.
Maybe it'd be possible to "feature-flag" such a new "improved" API or use another separated named output, say `MinimalPDFDocument` (or so, naming things is hard 🙈 )?


> I should also mention that `StandardFonts.Helvetica` is used internally by `pdf-lib`. This is why you can draw text and fill forms without specifying a font explicitly. I don't think it would be possible to tree-shake this.

That'd make sense, definitely! Still, removing the other 13 fonts would be an improvement already.

**Comment by lillallol** [comment]
@manniL Can you please post your webpack config and update it if needed or at least give exact versions of webpack, pdf-lib and loader dependencies? I am trying to reproduce what you are doing and I fail.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by MickL** [comment]
@Hopding I see the issue is closed. Has this been fixed?

**Comment by TheAlexLichter** [comment]
@MickL Sadly not, it is only tracked in https://github.com/Hopding/pdf-lib/discussions/998
