### ISSUE TITLE
React Native Application Crashes on React Native

### ISSUE THREAD

**Issue by FawadMahmood** [Hopding/pdf-lib#583]
PDF generation crashes on React Native while creating large PDFs.

**Comment by FawadMahmood** [comment]
I must say, it's really a mind blowing library, however due to less memory in mobile devices, I am having issues with ram memory and app crashes.

**Comment by FawadMahmood** [comment]
After Did some code changes in my code, I am able to get it work. Thank you for such a great library. 👍

**Comment by FawadMahmood** [comment]
Having issues while embedding a lot of images into PDF, it never loads up.

**Comment by punisher97** [comment]
You should be more specific, what is the error? screenshots, logs, PDF, code, images, etc...

**Comment by FawadMahmood** [comment]
> You should be more specific, what is the error? screenshots, logs, PDF, code, images, etc...

Thank you for your response, there's no error, it's just my mobile app freeze in Javascript thread. 

I am able to render records properly when count is not too much, when adding more images and data, this happens.

**Comment by FawadMahmood** [comment]
I will try make a video and post it here shortly.

**Comment by punisher97** [comment]
You can try modify parseSpeed and objectTicks

The purpose of making these methods asynchronous is to avoid blocking the event loop (especially for browser-based usage). If you aren't running this code client-side and are not concerned about blocking the event loop, you can speed up parsing times with:

```ts
PDFDocument.load(..., { parseSpeed: 2500 })
```

You can do a similar thing for save:

```ts
pdfDoc.save({ objectsPerTick: 2500 });
```

**Comment by Hopding** [comment]
Hello @FawadMahmood! I'm afraid what you're running into is a limitation of React Native. Due to React Native's architecture, only JSON data can be transferred into and out of the JavaScript VM. This means that in order to save a PDF file, it must be converted to a base64 string before it can be saved to the file system or rendered on the screen. This is a huge bottleneck, and it makes dealing with large files very difficult. 

Unfortunately, there's nothing that can be done in `pdf-lib` to solve this. Until the React Native team fixes this architectural issue, the best you can do is try to keep your file size down. Minimize the number of images you embed and try to reduce their size before embedding them.

Depending on what specifically you are trying to do, writing the file in changes may be helpful: https://github.com/Hopding/pdf-lib/blob/4046f3c61a5bed370473972d32c81c9869325919/apps/rn/src/tests/assets.js#L6

See also https://news.ycombinator.com/item?id=17316597 and https://github.com/facebook/react-native/issues/1424.
