### ISSUE TITLE
How to know if document is encrypted

### ISSUE THREAD

**Issue by mlecoq** [Hopding/pdf-lib#61]
Hi,

I am trying to migrate code from hummus to pdf-lib. With hummus there is a method ```isEncrypted()``` 

is-there any equivalent in pdf-lib ?

**Comment by Hopding** [comment]
This can be done. However, it's not as simple as an `isEncrypted()` method. I'm happy to share an example, but before I do so, I'd like to ask if you are planning on reading/modifying/manipulating encrypted documents in any way? `pdf-lib` does not currently support handling encrypted documents. So while you can detect that a given document is encrypted, you won't be able to do anything with it.

**Comment by mlecoq** [comment]
I have seen other issues about this topic where you reply it will not ne supported. In my case, my goal is to ignore encrypted file (so i have to detect them)

**Comment by Hopding** [comment]
In order to check if a document is encrypted, you'll need to tweak the [`PDFDocumentFactory.load`](https://github.com/Hopding/pdf-lib/blob/0c2b63760925d5eb687aedc0684e58f36c8e618b/src/core/pdf-document/PDFDocumentFactory.ts#L46-L89) method just slightly. 

I wrote an example Node script that does this, along with some encrypted and non-encrypted documents to illustrate that it works: [encryption-check.zip](https://github.com/Hopding/pdf-lib/files/2732872/encryption-check.zip)

To run the script:
```
unzip encryption-check.zip
cd encryption-check
yarn install # or `npm install`
node index.js
```

-----

Here's an excerpt from the script containing the encryption detection code:
```js
// Returns `parsedPdf` if document is not encrypted, `undefined` otherwise.
const parseIfNotEncrypted = (pdfParser, data, index) => {
  try {
    const parsedPdf = pdfParser.parse(data, index);
    const sections = parsedPdf.updates.concat(parsedPdf.original);

    // Check for "Encrypt" entries in trailer dictionaries (on older documents)
    for (const { trailer } of sections) {
      if (!!trailer.dictionary.getMaybe('Encrypt')) return undefined;
    }

    // Check for "Encrypt" entries in XRef streams (only on modern documents)
    for (const { body } of sections) {
      for (const { pdfObject } of body.values()) {
        if (pdfObject instanceof PDFRawStream) {
          const { getMaybe } = pdfObject.dictionary;
          if (getMaybe('Type') === PDFName.from('XRef')) {
            if (!!getMaybe('Encrypt')) return undefined;
          }
        }
      }
    }

    return parsedPdf;
  } catch (e) {
    // Most modern encrypted documents will fail to parse due to encrypted
    // object streams that we fail to decode. The `pako` library will fail
    // will the following String error, which we'll detect and handle here.
    const PAKO_ZLIB_ERR = 'incorrect header check';
    if (e === PAKO_ZLIB_ERR) return undefined;

    // If it's NOT a decoding error due to the document being encrypted, then
    // we'll rethrow the error.
    throw e;
  }
};

/**
 * Enhanced version pdf-lib's PDFDocumentFactory class, with new
 * "loadIfNotEncrypted" method designed to detect encrypted documents:
 *   https://github.com/Hopding/pdf-lib/blob/0c2b63760925d5eb687aedc0684e58f36c8e618b/src/core/pdf-document/PDFDocumentFactory.ts
 */
class CustomPDFDocumentFactory extends PDFDocumentFactory {
  /**
   * Loads an existing PDF document contained from the specified `Uint8Array`
   * into a [[PDFDocument]] object. Useful for modifying existing PDF documents.
   * Does not load encrypted documents.
   *
   * @param data A `Uint8Array` containing the raw bytes of a PDF document.
   *
   * @returns A [[PDFDocument]] object initialized from the provided document.
   *          Or `undefined` if the document is encrypted.
   */
  static loadIfNotEncrypted(data) {
    const index = PDFObjectIndex.create();
    const pdfParser = new PDFParser();

    // This entire method is the same as PDFDocumentFactory.load(), except
    // for the following 3 lines:
    const parsedPdf = parseIfNotEncrypted(pdfParser, data, index);
    const isEncrypted = !parsedPdf;
    if (isEncrypted) return undefined;

    const indexMap = PDFDocumentFactory.normalize(parsedPdf);
    index.index = indexMap;

    const pushGraphicsStateContentStream = PDFContentStream.of(
      PDFDictionary.from({}, index),
      pushGraphicsState(),
    );
    const popGraphicsStateContentStream = PDFContentStream.of(
      PDFDictionary.from({}, index),
      popGraphicsState(),
    );

    const { maxObjectNumber } = parsedPdf;
    const ref1 = PDFIndirectReference.forNumbers(maxObjectNumber + 1, 0);
    const ref2 = PDFIndirectReference.forNumbers(maxObjectNumber + 2, 0);

    index.assign(ref1, pushGraphicsStateContentStream);
    index.assign(ref2, popGraphicsStateContentStream);

    index.pushGraphicsStateContentStream = ref1;
    index.popGraphicsStateContentStream = ref2;

    return PDFDocument.from(parsedPdf.catalog, index);
  }
}
```

Let me know if you have any questions!

**Comment by kevinswartz** [comment]
Hi @Hopding ,
How hard would it be to add a method to the released library that would do this?  I'm also in the position of needing to ignore encrypted files, but I'm stuck using pdf-lib as a UMD module so I'd need to rewrite this.

**Comment by Hopding** [comment]
I might add an encryption check method eventually, but other bugs and features will take precedence over this for the forseable future.

Are you concerned about rewriting my code sample because it uses ES6+ JS syntax? If so, you could just [transpile it with Babel's REPL](https://babeljs.io/en/repl.html#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAECUFMBcFcCcB2BnUADADgQ3syATABXwDM1QBLE0fAewGNYBbSRaS1RW91--ATwzQCAGnSxE-SCQqIC5bgAtI8AO4U8AOgBQ9WinbZckAJIkActwCiiPoOH5QAXlAAKDKUI488MfizQWGKyUgAeAJTOAHygAN7aoKDQAnEJiaB6BqBGeESkztme3iqaOZCu_oHBkpARANxpiZnI7Hj00BT6qC5leSSasB4BkMiamfQB7sV9mrTwFADmslgANuENjaAgoADCyvQA1qAkc6AARDZ2QmegrMkUI5SISfBYFCsqNBTtnYg4D6hXPpQLQVlJ4DQGMw7shwpsThDXM12LEXm8PhCAL4g6htDpdSLxdLpKhuACEZOS6JK-G--L-Ak0CxgAFksPwAEblADklwEQm54Ui8BgCGeEikMjk-AaxMx2k22z2kEOx1OF1s_OgNzu80eslAAA0oLjkpAsExAfoVvwQc8mLRwc86IwWGxYfDTkiuijQBzHbbsbRcSr6bDUsTEgi3Mi4oUSAB5DkAK1DoCD1H9-H4mgAbqtYCNXEKI5HEqT3KQk6n2k8WlhbJBg6BCAARABi4CwqgAymaLYTNmXY6jmdA2ZzIOmCh5EynQ5paT99Dh-LKyyTqK4xxOua5uQAVQSQQXOJwuNvt8wWyCaEjwWhMffG6SCwcbyMVik79l73ma-w31AEU4CQUAJWkWQCHXD95Vgod002eVNhAsVsmmYgSHXbEJmgehFDcSB33SbYWVoFpQAdJ1bgAoQCEhV0YVAdQVhWY50SSWh0OMGhC04mirgcRUwFoedaxaEULVQaBFACZipxIDjoC4qQ9CkTRQAPZR0GwA5aHIFYKA5V4UhYtjFPeYTmPeNiZIU0EVlodREAWUA-3mFzbngB9fGYxRvgI1QT1YmgYDTBtHFkyQPlAZQRR0YlY0IABBABpBMAH0AC0ABkTAAIQyqxwHAApuVkPRvLTZQsHBDJ9gObkYMoLcp3PC80sy3KCqKkrhVFMCIKlaCFWJbYzEoaBuVQcwEwPUAsFCtTZFclQfN4qdlKSbSXWhNg_UgFaBK1URttYKygu5EKQMUB9VDOryfIS9IZLu25sO0TENmAAAqH6Eh-0AbCi-h6NzFRkF-eMAFpDI5aaWw7VsoTdaB2ywdo5ltegViwZBkDEdQZNAORVAB85HNqsxLGgPl7AIG4WBkx1QshhZpX4qRhFrXgTscXbUeQAAucnEkUaBoAwYWQCWGTYA5MZH2AAAJWgPBW4BZ1hozgA5RyOWAAAGegACYOQANgAZgAdnNw2AE4TYAVnwJ3IAtgAOa2sAIehDfNj2ABZICdj2SEt836A9yBzYARg9g3kHgehgEqyBNdIaGBbuYBL2Rxi2HRzHGWgZAAeAXRcfx3ZYBaR885Ru4i-UlJamESRUAbgu0YxlvbSJLY_saQGctoWrUAbW5Qg0DpPMvBi9vYTJAigxx70fB7kAwFUqAeRw0AAVVkaAPeS7z2TQYeni2xaAG1b67xeAF0n5BMToA0g-8BIWBzNOKiqD8COrUGeR157Z3dM9UAgNkaPC4OwSmjheb035o3SBw8r4AAEjAWhoAERayV0BHzYKfc-_ByDLzeIgI6dlgLdj9PwYQqBmyLXAWgj-GD0iA0wahJAqBCH30fqjF-b8azsFkBQDoqwKAAC96LryYA9DAD5cwUCkKg7uUDAYflAAmCEaAhqr3IKSWhEDxGoGQXRfAWiK6JHrB0egoBEHU2sLRBwFR8HESaD6J4YQCiXmrKGEwNRQhjEksIYszVYyzi8MYCELhSaI3bLEnwkTRokTAFpDQNEOgikojARQLNsm0OQDeBanckbsObljTQiDixiFqKDIQVloy0JOKxJyR1LZOKgsLTY0SML5B6MUFxtM3EEErCQFJKg_D4OqGEdY_SfEaDplYgoZJeiYWahWFZ4z8D9VAuKGow0ZTpO8VkEItQ2QYH8ZU7u1TGRcHgEwaRcipjGD6Is4klzQk_IKD865GxEo-IwLXRQABxV4GB_L0GQH2YYOx9Dt2gO5c0iiLwdkRWwO4qKLSzBIK4BCec6S_FXHeB8T5YiYnmbUcIIgEKguQBCqFMK4WBAiXSzYXz0jRLVpCrA0LvhsoRUinF_Z0VJKxci3FTB8WErLMS5cDIcwKNcFSmlER6VlgwHyllQr4Ucq1ekRZSysioheaEQJ7RzDMC5FiGcgysKmooiKEgsdbntmCbSEU7QTQqF4LeBENqmB2uQK4C1VroDBrtaAAA1KAWOYhDbcvOS66QJsPVeooD66AfqRSNjvHMaNENw1YEte_YtEJ40myTSa75ITNB4zZogVwrrE3ZDBfywVsKDWQClWKySTAU2-NqI2_GiwW2uprdkXVArWW9v7WwGVdaSQNsZcyud-r2V9tFUu8VBQ23bLXbO7twrhCLpRfulwU6gXpF4c8IRdxyWPnebkTCYx8GOQWBq7l8pMRAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=).

**Comment by mlecoq** [comment]
@Hopding thanks for your answer !

**Comment by kevinswartz** [comment]
Thanks @Hopding I was able to get this working today!

**Comment by ArchiReport** [comment]
@Hopding in a typescript project, normalize cannot be used:

```
Property 'normalize' is private and only accessible within class 'PDFDocumentFactory'.Propert ts(2341)
```

**Comment by mlecoq** [comment]
@Hopding in a typescript project, normalize cannot be used:

```
Property 'normalize' is private and only accessible within class 'PDFDocumentFactory'.Propert ts(2341)
```

**Comment by mlecoq** [comment]
Could it be protected ?

**Comment by mlecoq** [comment]
I've finally made a pull request : #81

**Comment by manuelkling** [comment]
@Hopding First of all: thank you for this great lib!

Is [https://github.com/Hopding/pdf-lib/issues/61#issuecomment-451935643](https://github.com/Hopding/pdf-lib/issues/61#issuecomment-451935643) still the only way to know if a document is encrypted? Not sure if/how [isEncrypted](https://pdf-lib.js.org/docs/api/classes/pdfdocument#isencrypted) helps here?

**Comment by abhineetkandele** [comment]
You can write these few lines of code in Vanilla JS to check if the PDF is password protected or not.

```
const reader = new FileReader();
reader.readAsArrayBuffer(file);
reader.onload = function () {

var files = new Blob([reader.result], {type: 'application/pdf'});
files.text().then(x=> {
    console.log("isEncrypted", x.includes("Encrypt"))
    console.log("isEncrypted", x.substring(x.lastIndexOf("<<"), x.lastIndexOf(">>")).includes("/Encrypt"));
    console.log(file.name);
});
```
