### ISSUE TITLE
Missing PDFDictionary entry "MediaBox"

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#62]
Hi @Hopding,
Sorry for another ticket, but I have another pdf that's throwing errors during drawText().  I'm trying to detect the size of the page, using this call, which I picked up from [here](https://github.com/Hopding/pdf-lib/issues/10#issuecomment-402326518)

```
var toHeight = page.get('MediaBox').array[3].number;
```

The file is attached, and here's the exception:

```
Error: Missing PDFDictionary entry "MediaBox".
    at error (pdf-lib.js:1061)
    at PDFPage.PDFDictionary$$1._this.get (pdf-lib.js:1953)
    at constructor.drawText (PDFGenerationHelper.js?_dc=1546970445137:97)
```
[text_only_pdfa1b.pdf](https://github.com/Hopding/pdf-lib/files/2737946/text_only_pdfa1b.pdf)

Thanks for your help!

**Comment by Hopding** [comment]
Hello @kevinswartz.

The error you are seeing is due to the fact that the page object itself doesn't have a `MediaBox` defined on it (hence no width/height). Instead, it's inherited from a parent node in the page tree. The code you are using to get the height happens to work for most documents, but is not general enough to work on all documents. 

Here is a function you can use to obtain the width/height of a page for any document:
```js
// Returns an object of shape: { width: number, height: number }
const getPageDimensions = (page) => {
  let mediaBox;

  // Check for MediaBox on the page itself
  const hasMediaBox = !!page.getMaybe('MediaBox');
  if (hasMediaBox) {
    mediaBox = page.index.lookup(page.get('MediaBox'));
  }

  // Check for MediaBox on each parent node
  page.Parent.ascend((parent) => {
    const parentHasMediaBox = !!parent.getMaybe('MediaBox');
    if (!mediaBox && parentHasMediaBox) {
      mediaBox = parent.index.lookup(parent.get('MediaBox'));
    }
  }, true);

  // This should never happen in valid PDF files
  if (!mediaBox) throw new Error('Page Tree is missing MediaBox');

  // Extract and return the width and height
  return { width: mediaBox.array[2].number, height: mediaBox.array[3].number };
};
```

You can use it like so:
```js
const pdfDoc = PDFDocumentFactory.load(pdfBytes);

const firstPage = pdfDoc.getPages()[0];
const dims = getPageDimensions(firstPage);

console.log('First page width:', dims.width); 
console.log('First page height:', dims.height); 
```

I'm planning on adding this to `pdf-lib`'s API soon. But in the meantime, I'll make a note about this in the issue you linked to. Hopefully that will help others avoid encountering the same error.

**Comment by Jobin-S** [comment]
hlo
