### ISSUE TITLE
"Error: Expected instance of PDFDict or PDFStream, but got instance of undefined" on save()

### ISSUE THREAD

**Issue by schlosser** [Hopding/pdf-lib#623]
I have a funky (possibly corrupt) PDF that fails to fill. When I run `save()`, I hit the following error:

```
Error: Expected instance of PDFDict or PDFStream, but got instance of undefined
    at new UnexpectedObjectTypeError (/path/to/myproject/node_modules/pdf-lib/cjs/core/errors.js:40:24)
    at PDFContext.lookup (/path/to/myproject/node_modules/pdf-lib/cjs/core/PDFContext.js:78:15)
    at PDFDict.lookup (/path/to/myproject/node_modules/pdf-lib/cjs/core/objects/PDFDict.js:51:43)
    at PDFWidgetAnnotation.PDFAnnotation.getAppearances (/path/to/myproject/node_modules/pdf-lib/cjs/core/annotation/PDFAnnotation.js:75:20)
    at PDFTextField.needsAppearancesUpdate (/path/to/myproject/node_modules/pdf-lib/cjs/api/form/PDFTextField.js:619:48)
    at PDFForm.updateFieldAppearances (/path/to/myproject/node_modules/pdf-lib/cjs/api/form/PDFForm.js:460:23)
    at PDFDocument.<anonymous> (/path/to/myproject/node_modules/pdf-lib/cjs/api/PDFDocument.js:1150:38)
    at step (/path/to/myproject/node_modules/tslib/tslib.js:141:27)
    at Object.next (/path/to/myproject/node_modules/tslib/tslib.js:122:57)
    at /path/to/myproject/node_modules/tslib/tslib.js:115:75
```

I was able to fix this locally by adding a `try{}catch{}` around `needApperancesUpdate`. Should there be some way to fail gracefully here? Or any idea why the error might be happening?

The PDF: [CCC901.pdf](https://github.com/Hopding/pdf-lib/files/5344075/CCC901.pdf)

**Comment by Wian-TMC** [comment]
I have a similar issue and the try catch resolved the issue locally. I wonder if this is caused if not all fields are filled in?

**Comment by schlosser** [comment]
Hmm I don't think so; I definitely am able to leave many fields blank in many different PDFs. Although it could be related to leaving some fields blank in certain types of PDFs?  Do you have a reason to believe the empty fields would cause this?

**Comment by Wian-TMC** [comment]
No probable reason no. The PDF I am working on does have fields used for calculations to populate others though. But all I have are assumptions to what might be going wrong. The try-catch block catches the error and allows everything to work as it should without inducing any errors on the PDF document.

**Comment by aman-saraf** [comment]
@schlosser . I don't think that adding try catch block locally is a good idea. From my investigation, it looks like that the PDF document is corrupt. It seems that the `pdf-lib` expects the PDF in some standards, even though the `load` method won't throw error for a corrupt pdf file.

In order to check whether your pdf file is compliant with standards, you may use online checkers such as https://www.pdfen.com/pdf-a-validator .  Most probably, it will notify you of the errors & you may convert the pdf into specific standard & try again . 

I hope it helps !

**Comment by Wian-TMC** [comment]
@aman-saraf . You champion. I converted the PDF to the PDF/A standard and it worked beautifully. I have tried setting the 'updateFieldAppearances' to false, but it obscured the editable text field by only showing the text once you click on the field. Note that that could also have been because the format of the PDF was incorrect.

Nonetheless, converting the PDF worked 👍

**Comment by aman-saraf** [comment]
@Wian-TMC . Glad to know that it worked for you. Yeah, you're correct in pointing the flaw in `updateFieldAppearances`. The conversion of `PDF` standard to `PDF/A` standard seems to be the best solution.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
