### ISSUE TITLE
Embedded pages are uncompress

### ISSUE THREAD

**Issue by ferjul17** [Hopding/pdf-lib#639]
Hi,

I'm migrating our pdf generation tool from [`HummusJS`](https://github.com/galkahana/HummusJS) to [`pdf-lib`](https://github.com/Hopding/pdf-lib).

I have to merge two pdf pages into a new pdf. To achieve that I embed the pages into a new pdf document.
The size of the generated file is significantly increased compared to the original one.
When I compress the generated pdf, the file size is closer than what I expect.

I did a test case to show the issue:

```typescript
import {readFileSync, writeFileSync} from 'fs'
import {PDFDocument} from 'pdf-lib'

(async () => {

    const pdfDoc = await PDFDocument.create();

    const pdfSource = await PDFDocument.load(readFileSync('./Lorem ipsum dolor sit amet.pdf'));
    const embeddedPage = await pdfDoc.embedPage(pdfSource.getPage(0));

    const page = pdfDoc.addPage();
    page.drawPage(embeddedPage);

    writeFileSync('embedded.pdf', await pdfDoc.save());

})();
```

The source file is a simple pdf of 200 KB made with Word : [Lorem ipsum dolor sit amet.pdf](https://github.com/Hopding/pdf-lib/files/5402220/Lorem.ipsum.dolor.sit.amet.pdf)
The file generated by this script is 1.5 MB. It's 7.5x larger : [embedded.pdf](https://github.com/Hopding/pdf-lib/files/5402223/embedded.pdf)

I think that the LZW stream from the source file is uncompressed before being embedded into the new PDF file.

Am I correct?

**EDIT:** I inspected both PDF and I found a FlateDecode stream in the source pdf which is decoded in the destination pdf.
![Screenshot 2020-10-20 at 09 48 14](https://user-images.githubusercontent.com/1574473/96834600-8d8a9a00-1442-11eb-971b-9bbe4a54fff4.png)

Regards,

Julien

**Comment by ferjul17** [comment]
I found a workaround. After generating the PDF I use Ghostscript to "compress" it. `gs -o embedded.gs.pdf -sDEVICE=pdfwrite -dBATCH -dNOPAUSE embedded.pdf` is enough to "restore" DeflateStreams and reduce the size of the generated PDF. 

After that operation I get a PDF of 212 KB: [embedded.gs.pdf](https://github.com/Hopding/pdf-lib/files/5429263/embedded.gs.pdf)

**Comment by SvV-CWinJS** [comment]
Hi,

I would like to request a compression of the pdf by pdf-lib as well. I'm having te same problem and since I'm working in a pure Javascript environment, I can't use a tool like Ghostscript to compress the pdf.

The 2 source pdf's are 600kB and the resulting pdf is 5MB.

Regards,
Sven

**Comment by viniferrareze** [comment]
Hi, I would like to request a compression of the pdf by pdf-lib as well. Deadline approve PR ?

**Comment by tobiasfuhlroth** [comment]
I also face a problem related to uncompressed embedded pages. In my scenario i want to apply a page background (letter paper) to every page of a content PDF. The only way i found to achieve this is to embed both the page background and all content pages to a new PDF and then draw them in the correct order on newly created pages.

So far, so good. But because the embedded pages are not compressed the final PDF has a size of approx 750 KB instead of 85 KB. Those values are for a 5 page PDF. If i do the same with 50 pages i end up with over 8 MB.

With the proposed change in the [PR](https://github.com/Hopding/pdf-lib/pull/817) i end up with approx 125 KB for the 5 page PDF which is fine.

@Hopding Any chance this PR get's accepted and released? Is there anything i can do to get this done?
