### ISSUE TITLE
copyPages() and removePage() methods contains PDFRawStream data of original file

### ISSUE THREAD

**Issue by aareeph** [Hopding/pdf-lib#656]
I want to split multi pages pdf into separate single page PDF files. I have used the following code to copy single page to separate PDF but I noticed that the overall size of the destination files remains same. Moreover, PDFRawStream data in the destination files shows the data from the original PDF.

`for (i = 0; i < sourcePdfDoc.getPages().length; i++) {
    var destPdfDoc = await PDFDocument.create();
    var [currentPage] = await destPdfDoc.copyPages(sourcePdfDoc, [i]);
    destPdfDoc.addPage(currentPage);
    var pdfBytes = await destPdfDoc.save();
  }`

I tried another approach to make a duplicate of source pdf file and remove pages from it but the issue remains the same i.e. the resulting PDF consists of same size and shows PDFRawStream data of source file.

Thanks!

**Comment by Hopding** [comment]
Hello @aareeph! This might be because each page of your PDF relies upon the same assets (fonts, etc...). So even when you split them apart, the bulk of the original file still needs to copied into the new ones. If you don't think this is the cause of your issue, please share complete working code and sample PDFs that I can use to reproduce the issue.

**Comment by irtzasuhail** [comment]
is there any way we can remove that extra information? flatten the PDF or remove the assets or something?
