### ISSUE TITLE
Font Subset Embedding fails

### ISSUE THREAD

**Issue by mbiegert** [Hopding/pdf-lib#664]
Hi, I've ben using the cool labelmake library which embeds fonts using the `subset` option. As it does so, I've discovered a bug in `pdf-lib` itself.

A font (Futura PT Book in my case) that is embedded with `{ subset: true }` fails to render properly in some cases. It simply does not show the text when I open the pdf with gnomes standard "DocumentViewer" evince, see the screenshot.
![image](https://user-images.githubusercontent.com/22346012/98516003-37a05980-226c-11eb-9e67-2529532936e5.png)

It renders the text with a fallback font on chrome(ium).
![image](https://user-images.githubusercontent.com/22346012/98516124-5f8fbd00-226c-11eb-913c-087b79040ccb.png)

And it works fine when viewing the pdf in firefox or electron (vscode).
![image](https://user-images.githubusercontent.com/22346012/98516577-fb212d80-226c-11eb-8b93-771f21300867.png)

I've created a small test repository to show case this at https://github.com/mbiegert/pdf-bug.

Subset embedding standard fonts does work as normal.

Do you think this might be related to the particular font?

**Comment by Hopding** [comment]
Hello @mbiegert! Please see https://github.com/Hopding/pdf-lib/issues/494#issuecomment-695818400. Aside from investigating and fixing the root cause of the issue, I would suggest trying to use a different font or else disabling subsetting (if `labelmake` provides an option for doing so - if not, I'd recommend you discuss adding one with the author of `labelmake`).
