### ISSUE TITLE
React Native: Require cycles

### ISSUE THREAD

**Issue by mateosilguero** [Hopding/pdf-lib#666]
using it on react native display this warning:

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/pdf-lib/cjs/api/PDFDocument.js -> node_modules/pdf-lib/cjs/api/PDFEmbeddedPage.js -> node_modules/pdf-lib/cjs/api/PDFDocument.js
Require cycle: node_modules/pdf-lib/cjs/api/PDFDocument.js -> node_modules/pdf-lib/cjs/api/PDFFont.js -> node_modules/pdf-lib/cjs/api/PDFDocument.js
Require cycle: node_modules/pdf-lib/cjs/api/PDFDocument.js -> node_modules/pdf-lib/cjs/api/PDFImage.js -> node_modules/pdf-lib/cjs/api/PDFDocument.js
Require cycle: node_modules/pdf-lib/cjs/api/PDFDocument.js -> node_modules/pdf-lib/cjs/api/PDFPage.js -> node_modules/pdf-lib/cjs/api/PDFDocument.js
```

Thats why some files are calling them recursively.

PDFImage imports PDFDocuments,  and viceversa.

**Comment by Hopding** [comment]
Hello @mateosilguero! 

Thanks for the notification. I'm aware that `pdf-lib` contains circular imports. However, all such circular imports should be safe and should not result in uninitialized values. If you find that the circular imports are causing errors, please do let me know. Otherwise I do not have any plans to remove them in the short-term (though I've considered doing so in the next major release of pdf-lib).

Note that if they are not causing errors, it should be possible to suppress the warnings. Though I don't know what the specific API for doing so is in the current version of React Native. If you end up doing this, please do share the code!
