### ISSUE TITLE
The output file size is bigger than the original by 15 times after drawing a text to the pdf file.

### ISSUE THREAD

**Issue by amirhamdy4IN3** [Hopding/pdf-lib#669]

**Comment by Hopding** [comment]
Unable to reproduce. Please share create a working example with code and a PDF that I can use to reproduce the issue.

**Comment by vlio20** [comment]
@Hopding I think that the issue is happening when embedding a large font file. 
```
pdfDoc.registerFontkit(fontkit);
const font = await this.fetchFont();
await pdfDoc.embedFont(font);
```
by excluding the last line the file size is norma. 

Any suggestion on how to overcome this? I am using the Arial font family to support multiple languages (in my app I don't know in advance what would be the input language).

**Comment by Hopding** [comment]
@amirhamdy4IN3 Please see my response to @vlio20 inhttps://github.com/Hopding/pdf-lib/issues/725.
