### ISSUE TITLE
Cost of font embedding

### ISSUE THREAD

**Issue by ScreamZ** [Hopding/pdf-lib#670]
Hi,

I'm dealing with a document collection app. I've pieces of document that the user should upload, for each one I generate a new PDF and add a text at the top of each page (1page = 1 image + text) using `embedStandardFont` each time on the document.

Then Each time the user has finished scanning all page for a document, I merge all created pages into another ROOT document.

My question is, at each page inserted I call `const font = await this.pdfDocument.embedFont(StandardFonts.Helvetica);`, is there any cost (great one ?) in terms of Ko of calling this multiple time or the client is smart enough to ensure de-duplication?

Thanks,
Andréas

**Comment by Hopding** [comment]
Hello @ScreamZ! 

There is a cost to calling `embedFont` - even if you pass the same font each time. pdf-lib does not do any internal caching to avoid duplication. Note that the cost of embedding a standard font is fairly small. The cost of embedding a custom font is much larger. I recommend caching all fonts and calling `embedFont` as few times as possible (*especially* for custom fonts). This is what pdf-lib does internally anytime it needs to embed and use a font: https://github.com/Hopding/pdf-lib/blob/30d2aa22c0c0d694189ae3202562d4c0565cce42/src/api/form/PDFForm.ts#L78

**Comment by ScreamZ** [comment]
Alright, in fact, I'm playing with a lot of pages that I manipulate.

I have a document scanner and when a new document is being scanned I create a new pdg and embed font, then when all pages are scanned, I copy pages into the main document,the thing is that I require font embedding each time a new document is created.

Whats the behavior when merging?do I need to include the font in the root document only? Or I have no choice to embed one time per document then merge?

**Comment by Hopding** [comment]
The simplest option would be to embed once per document (assuming you’re drawing text on the documents prior to merging). It’s theoretically possible to remove duplicate fonts after merging, but you’d have to figure this out on your own using pdf-lib’s low-level APIs. Since it’s not an official feature provided by pdf-lib, I wouldn’t have time to help you implement it. But again, if you’re embedding standard fonts, doing one embed per document isn’t going to be too expensive.
