### ISSUE TITLE
Text field switches fonts when editing

### ISSUE THREAD

**Issue by ajaishankar** [Hopding/pdf-lib#674]
@Hopding This is follow up to issue https://github.com/Hopding/pdf-lib/issues/663

Attaching the [original.pdf](https://github.com/Hopding/pdf-lib/files/5542793/original.pdf) and [filled.pdf](https://github.com/Hopding/pdf-lib/files/5542795/filled.pdf)

**Test**:

1. Find the first text field and update the text to "Courier Bold" using `StandardFonts.CourierBold`

**Issues**:

1. The filled field displays properly in Courier Bold. But changes to Helvetica when focused and after an edit (Rest of the fields which are untouched behave normally)

2. pdf-lib is not able to identify all the fields in this form - it is able to recognize only 2 fields in this form

This is the code I am using:

```
async function processPdf(srcPath: string, destPath: string) {
  const srcBytes = readFileSync(srcPath)
  const doc = await PDFDocument.load(srcBytes)

  const courierBold = doc.embedStandardFont(StandardFonts.CourierBold)

  const form = doc.getForm()
  const fields = form.getFields()

  console.log(`doc has ${fields.length} fields`)

  const textField = fields.find((f) => f instanceof PDFTextField) as PDFTextField

  if (textField != null) {
    textField.defaultUpdateAppearances(courierBold)
    textField.setText('Courier Bold')
  }

  form.updateFieldAppearances(courierBold)

  const destBytes = await doc.save({ updateFieldAppearances: false })

  writeFileSync(destPath, destBytes)
}
```

**Comment by mrlowe** [comment]
I'm joining this issue from #663 because it seems like what I'm seeing might be related.

I also gave `updateFieldAppearances: false` a shot, but it appears to have some strange effects on multiline fields: in Firefox on mac the text doesn't break at the linebreaks, and in Acrobat DC the linebreaks are displayed, but text fields (multiline or otherwise) don't show the field contents unless you click on them (!??). Everything looks fine in Preview. Linebreaks are also preserved if no value is set for `updateFieldAppearances` on save.

It's reproducible by writing to any of the multiline fields in [dod_character.pdf](https://github.com/Hopding/pdf-lib/blob/master/assets/pdfs/dod_character.pdf) and then saving with `updateFieldAppearances: false`.

If this is one or more distinct problems, I'd be glad to create a separate Issue.

**Comment by mrlowe** [comment]
@ajaishankar I've noticed that I get different behavior depending on the order I call `setText()` and `defaultUpdateAppearances()`. What happens in your test code if you call `setText()` first?

**Comment by EvilTables** [comment]
Any updates on this? I'm not entirely sure how to change the font when inputting text into form fields. I think the docs could definitely be more explicit on how to do this.

**Comment by EvilTables** [comment]
To clarify, I'm having the same issue as mrlowe above. When using updateFieldAppearances: false, the form fields have their original styling but cannot be seen until they are clicked on, which is strange.

**Comment by Hopding** [comment]
`pdf-lib` doesn't currently provide a way to control the preferred font of a field. If you use don't use the preferred font for a field when you fill it, then you'll see this font-switching behavior. Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998
