### ISSUE TITLE
How to map mouse position on browser to pdf page position (x, y)

### ISSUE THREAD

**Issue by fuminori-ido-m** [Hopding/pdf-lib#694]
Is there any way to know pdf page position (x, y) of mouse on browser?

What I would like to do is to add a simple mark (e.g. "DONE" text or some small icon) when clicking mouse on pdf page in browser.

In #346 @Hopding says:

> pdf-lib has no built-in way to interact with edits the user makes in the iframe. However, if you have some other way of knowing what the user has done to edit the PDF (e.g. by rendering an HTML form instead of a PDF), you could use pdf-lib to map these changes into PDF modifications

I understand that:

- getting info from pdf document in iframe is not supported by pdf-lib, but
- modifying pdf document can be done by pdf-lib.

So that it is possible to add icon and/or fixed-text by pdf-lib, but I wonder how to specify page position (x, y) when mouse clicking on the browser.

I very appreciate if there is any way to know that.

**Comment by Hopding** [comment]
I don't think this is to do with iframes. There simply if no browser API to get information about a PDF document outside of the iframe. You might try using https://github.com/mozilla/pdf.js or a derivative library to render the document instead of an iframe. `pdf.js` is implemented entirely in HTML/JS/CSS, so it can provide APIs to find out how a user is interacting with the document.
