### ISSUE TITLE
Error: Invalid Stream!

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#70]
Hi @Hopding 
I've got one more for you.  I'm on v0.6.1-rc2.  I'm unable to attach the pdf here because it has some private information in it, however I could send it to you privately.  Please let me know the best way to do this.  Thanks again!

```
Error: Invalid Stream!
    at error (pdf-lib.js:8569)
    at parseStream (pdf-lib.js:46840)
    at parseStream$1 (pdf-lib.js:46870)
    at parseDictOrStream (pdf-lib.js:46913)
    at parseIndirectObj (pdf-lib.js:46947)
    at parseBodySection (pdf-lib.js:47174)
    at parseDocument (pdf-lib.js:47226)
    at PDFParser.parse (pdf-lib.js:47257)
    at Function.PDFDocumentFactory.load (pdf-lib.js:47379)
```

**Comment by Hopding** [comment]
Hello @kevinswartz. 

Please send the document to me via email (andrew.dillon.j@gmail.com).

I suspect the cause of this error is a corrupted/invalid PDF. Probably similar to https://github.com/Hopding/pdf-lib/issues/68/https://github.com/Hopding/pdf-lib/issues/69 or https://github.com/Hopding/pdf-lib/issues/73. I'll let you know what I find once I receive the document.

**Comment by Hopding** [comment]
Hello again @kevinswartz. I had a chance to look into this today. 

The document you emailed me actually contains a nested PDF file within itself. This is called an _embedded file_. Embedded files are pretty rare from what I've seen. I actually haven't come across one before. However, `pdf-lib` would normally be able to parse them without issue. The reason it is failing in this case is because the embedded PDF file is unencoded. This really throws off the `pdf-lib` parser, because it doesn't realize it's moved from parsing the main PDF file to parsing the embedded one.

Anyhow, this is a perfectly valid PDF that `pdf-lib` should be able to parse. I'm working on a fix for this. I don't think it will require too big of a change to the parser. I'll let you know once I've made more progress.

**Comment by Hopding** [comment]
@kevinswartz I found the bug causing this issue and fixed it in https://github.com/Hopding/pdf-lib/pull/77.

I just cut prerelease [`0.6.1-rc4`](https://www.npmjs.com/package/pdf-lib/v/0.6.1-rc4) with the fix.

You can install this prerelease with npm:
```
npm install pdf-lib@0.6.1-rc4
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.1-rc4/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.1-rc4/dist/pdf-lib.min.js

Please try it out and let me know if it works for you!

**Comment by kevinswartz** [comment]
Looks fixed to me.  Thanks for your help!
