### ISSUE TITLE
How to create a file with multiple supported languages

### ISSUE THREAD

**Issue by vlio20** [Hopding/pdf-lib#725]
Hi,
In my use-case the pdf document might contain texts from multiple languages. Embedding some unicode font 
(like Arial MS)  is not an option as it blows the size of the file to many MBs instead of few KB. 

When creating a pdf document from a docx file (via google docs for example) which contains multiple languages the file size is very small (few KBs). 

What might be the solution for such a use-case?

**Comment by Hopding** [comment]
Hello @vlio20!

You can subset a font so that the resulting document only includes the data pertaining to glyphs that were actually drawn on a page as opposed to including the entire font and all its glyphs. See https://github.com/Hopding/pdf-lib/issues/207#issuecomment-537210471. But note that font subsetting isn't bullet-proof, so you may have to fiddle around with the fonts you're using to find one that will work (see https://github.com/Hopding/pdf-lib/issues/664 and https://github.com/Hopding/pdf-lib/issues/494#issuecomment-695818400).
