### ISSUE TITLE
App crashes when feeding large dataset

### ISSUE THREAD

**Issue by pedro-surf** [Hopding/pdf-lib#728]
Electron exited with code 4294930435

![image](https://user-images.githubusercontent.com/40304742/103425889-2e5caa80-4b94-11eb-9cd8-dccec3251ce6.png)

When saving, it crashes. One of the files which seems to cause the issue is a one-page document, filled with pictures.

![image](https://user-images.githubusercontent.com/40304742/103425921-69f77480-4b94-11eb-9f4f-7ca1976399eb.png)

**Comment by Hopding** [comment]
Hello @pedro-surf!

Can you please provide a script and PDF that I can use to reproduce the issue?

**Comment by Hopding** [comment]
Woops, didn't mean to hit the close button 😄

**Comment by pedro-surf** [comment]
We've sent you the links for the script and the files. Did you receive it on your email?

**Comment by Hopding** [comment]
Don't see any emails. Are the documents private or confidential?

**Comment by pedro-surf** [comment]
https://drive.google.com/file/d/1WFs45uJKpMmBiwXZvaBnO2T4AO2K-t_n/view

[script.txt](https://github.com/Hopding/pdf-lib/files/5760843/script.txt)

**Comment by Hopding** [comment]
Looks like a memory issue. pdf-lib works entirely in-memory. It's doesn't do any I/O streaming or file buffering. See https://github.com/Hopding/pdf-lib/issues/197. 

The total size of all the documents you shared is 2.1 GB. This means that pdf-lib needs to allocate a 2.1 GB buffer in memory to serialize the final document. I'm sure this is why your program is crashing. When I ran it on my machine, `node` crashed and told me it couldn't allocate a `Uint8Array` of that size, which isn't terribly surprising.

It appears that the documents you're merging are so large because they contain very high resolution images. I'd suggest trying to lower the resolution of the images prior to embedding them in the source documents, if possible. 

Aside from that, the only solution I can think of is to implement I/O streaming in pdf-lib. Implementing full support for I/O streaming across the entire library would be a fairly intensive task. But just streaming the output file actually would be fairly straightforward and I suspect would solve your problem. See https://github.com/Hopding/pdf-lib/issues/239#issuecomment-623794825. If you're interested in working on this, I'd be happy to provide pointers! (Just be aware that you'll still end up with a 2.1 GB PDF document).
