### ISSUE TITLE
What objects in the context are not affected by flattening (Notability)?

### ISSUE THREAD

**Issue by jbeuckm** [Hopding/pdf-lib#729]
I need to write a string to the PDF (not visible or metadata) that can be read back later after the PDF is edited with Notability. I tried to embed an image with the data but after the user edits in Notability, the embedded images are gone - I assume because of flattening.

What kind of object could be written to the context that will stay the same after editing/flattening in Notability?

**Comment by Hopding** [comment]
Looks like you identified hidden fields as a solution in https://github.com/Hopding/pdf-lib/pull/730, so I'll go ahead and close this for now. 

Note also that in addition to adding a field to a page and then hiding it, it should also be possible to simply create a field and set its value without ever adding it to a page in the first place.

**Comment by Hopding** [comment]
Actually, I'm not sure if hidden fields will necessarily be excluded from a flattening operation, so that may not address this issue. Looks like you've already come across https://github.com/Hopding/pdf-lib/issues/593#issuecomment-693711236. You could register whatever kind of object you want in the document by using `pdfDoc.context.register(...)`.
