### ISSUE TITLE
Object.values polyfill

### ISSUE THREAD

**Issue by Crunchyalex** [Hopding/pdf-lib#74]
Hello Hopding! Thanks for the great library, it's been very useful so far.

I've been struggling with getting it compatible with IE11, though. 
Do you have any idea how to get around polyfilling the Object.values() method? 

Perhaps I'm just unaware of a good solution, core-js doesn't seem to help me here..

**Comment by Hopding** [comment]
Hello @Crunchyalex. I'm glad you're finding `pdf-lib` useful.

I don't think you can really get around polyfilling the `Object.values()` method, since it's used in the distribution builds. Is there a reason you don't want to polyfill it? It looks like there are at least two good polyfills available:
* https://github.com/tc39/proposal-object-values-entries
* https://github.com/es-shims/Object.values

**Comment by Hopding** [comment]
I'm going to close this for now. But, please feel free to reopen if you have any further questions!
