### ISSUE TITLE
tsconfig compiler target should be bumped from ES5 to ES2016

### ISSUE THREAD

**Issue by mcshaz** [Hopding/pdf-lib#747]
Multiple pieces of code within this library use ES2015 & occasional ES2016 standard syntax (including ES2015 methods like Array.from, Object.keys and the Map object and ES2016 methods like Array.prototype.includes). There are comments in the code about whether such methods should be poly-filled.

I would suggest it is the consuming code's responsibility to polyfill if that is a requirement, but the `tsconfig.json` `compilerOptions.target` should reflect the ECMAScript standard being used in the code base, which is ES2016, not ES5.

**Comment by simonbuchan** [comment]
This description is weird. The point of `target` is to tell typescript which target ES version to compile the *syntax* down to. You don't get to polyfill if you load code using higher syntax versions. The normal usage is to use the latest supported ES features and `target` will downlevel to your target environment (hence the name). If you then use *runtime* features (like `Map`, `Object.keys`, etc.) you would need a polyfill. If you want to avoid doing that, you can set the compiler option `lib` to include e.g. `es2017`.

The real problem is there's basically no reason to target anything lower than es2019: every supported version of every environment [supports everything up to that](https://kangax.github.io/compat-table/es2016plus/) (excluding Spectre mitigations and the exact format of Function#toString() on iOS). Not doing so means `async` functions (an es2017 feature) are downleveled, which breaks error async stacks and worsens bundle size and performance.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998. Changing the compiler target can have big, unintended side effects for consumers so I'll have to think carefully before doing something like this.

@simonbuchan appreciate your notes on the advantages of updating to a newer target 👍.
