### ISSUE TITLE
Form flattening for FDF field with embedded font

### ISSUE THREAD

**Issue by c0nstructer** [Hopding/pdf-lib#779]
Hi,

I have following code where flatten makes me issue:

```javascript
let field = form.getTextField(foundTemplate.fdfFieldName);
let overallText = assetData.text;
field.setText(overallText)
const embededFont = await embedFont(pdfDoc, foundTemplate.type.font.family, foundTemplate.type.font.style)
field.defaultUpdateAppearances(embededFont);
```

After this code, when i call
`form.flatten()`
I get flattened form, but without embedded fonts. Images after flatten also appear nicely.
When i remove flatten, i get proper font embed, text is on certain font, but images are not displayed.
Also tried with `form.flatten({updateFieldAppearances: false})` I get blank text.

Could be issue on flattening form?

**Comment by tw1t611** [comment]
Since the issue was opened half a year ago. Could anyone share a workaround?

At least for me one of these options would fit:

1. Form does not get flattened and pictures are shown
2. Form does get flattened and AcroForms remain font family / style
3. You can choose which fields to flatten
4. You can change text font after flattening

**Comment by Hopding** [comment]
@tw1t611 always happy to accept PRs :)

Perhaps the doc comments could be updated for https://pdf-lib.js.org/docs/api/classes/pdftextfield#defaultupdateappearances and/or https://pdf-lib.js.org/docs/api/classes/pdftextfield#updateappearances?
