### ISSUE TITLE
Removing fontkit if only merging/splitting pdfs

### ISSUE THREAD

**Issue by Subtletree** [Hopding/pdf-lib#82]
Hey!

My use of pdf-lib currently is only merging, splitting and removing pages from pdf's. I've looked over #14 and am I right that a `pdf-lib` fork with all fontkit references removed would still work for me?

Loving the library by the way, cheers!

**Comment by Hopding** [comment]
Hello @Subtletree. I'm glad you're finding the library to be useful!

Yes, if you are not embedding non-standard fonts, you should be able to safely remove the `@pdf-lib/fontkit` dependency and all references to it. That should significantly reduce the resulting bundle size.

Note that if you writing your JS code with ES6 `import`/`export` statements, and are using a tree-shaking bundler (like [Rollup](https://rollupjs.org/guide/en#tree-shaking) or [Webpack](https://webpack.js.org/guides/tree-shaking/)) then your bundler should automatically detect that you're never using `@pdf-lib/fontkit`, and won't place it in the bundle. This should allow you to avoid forking `pdf-lib` and making changes. Of course, if you aren't using a bundler, then tree-shaking isn't an option for you.

P.S. If you're interested, I'd like to figure out a way to produce `pdf-lib` UMD builds that don't include `@pdf-lib/fontkit`. That way users that aren't using bundlers can opt for a smaller bundle. I won't have time to work on this for the forseeable future. But if you're interested in working on it (rather than maintaining a separate fork), I'd be happy to help answer any questions you might have.

**Comment by Hopding** [comment]
I'm going to close this issue for now. Please feel free to reopen it if you have any additional questions!

**Comment by Subtletree** [comment]
Thanks for your response @Hopding and sorry for not replying earlier.

Good point about tree shaking, the way I'm building at the moment doesn't do any shaking of sub modules but likely will do soon so I'm happy with that for now. 

If in the future i'm still loading fontkit unnecessarily then I'll take a look at producing a separate build not including it. Definitely a better option that forking!
