### ISSUE TITLE
Modify Document (pdf-lib) Fiddle doesn't work with other PDFs

### ISSUE THREAD

**Issue by mickeydelo** [Hopding/pdf-lib#920]
How come if I replace the PDF URL (https://pdf-lib.js.org/assets/with_update_sections.pdf) in [this Fiddle](https://jsfiddle.net/Hopding/64zajhge/1/) it with the same PDF, but a different URL ( (https://github.com/Hopding/pdf-lib/blob/master/assets/pdfs/with_update_sections.pdf)) it doesn't work?

**Comment by Hopding** [comment]
Because https://github.com/Hopding/pdf-lib/blob/master/assets/pdfs/with_update_sections.pdf doesn't link to a PDF, it links to an HTML/JS page that renders a PDF preview. You have to provide a link to a raw PDF file, like so: https://github.com/Hopding/pdf-lib/raw/master/assets/pdfs/with_update_sections.pdf.
