### ISSUE TITLE
What is the maximum file size of a final mergedPDF document  that pdf-lib supports? We have a scenario where in we may have to merge 1000s of PDF documents and generate a 50 to 100GB file ?

### ISSUE THREAD

**Issue by laarani** [Hopding/pdf-lib#936]

**Comment by laarani** [comment]
Very good info that shares on the max size of a PDF file. The response in Adobe community was in 2012.
https://community.adobe.com/t5/acrobat/is-there-a-pdf-size-limit/m-p/12177317#M320889

" Architecturally there is only one limit in the PDF standard: the overall file size must be below ~10GB as the cross-reference tables which define the PDF structure use 10 bits."

Now it is 2021:-)
1.is there any update or change in the limitation or cross-reference tables that define the PDF structure uses more than 10 bits .?
2.is there a update from pdf-lib  implementation that aligns with PDF standard -"the overall file size must be below ~10GB as the cross-reference tables which define the PDF structure use 10 bits"
3.Is there an update from the pdf-lib implementation to handle  file size greater than 10GB file size?

Appreciate the responses.
-PDF lover

**Comment by 921451861** [comment]
Hello, why does the merged PDF fail to save when it is larger than 2G

**Comment by Hopding** [comment]
I'm pretty sure PDFs can be arbitrarily large now that cross reference streams are supported.

That being said, `pdf-lib` can only handle documents that fit into memory. This is because i/o streaming is not currently supported. I'd like to add it to a future version though. See https://github.com/Hopding/pdf-lib/issues/990 and https://github.com/Hopding/pdf-lib/discussions/998.
