### ISSUE TITLE
How to get all trailer data

### ISSUE THREAD

**Issue by ealloradai** [Hopding/pdf-lib#939]
Hi all, I'm trying to use pdf-lib to manually make some incremental updates to PDF files. To create an update I should recreate the XRef table, but I cannot find a way to get if the XRef is a table or a stream. In the trailerinfo object I found only "Info" and "Root" entries and not infos about the Type. How can i get this finformation? Thanks.

**Comment by PhakornKiong** [comment]
Hello there, the `trailerDict` is always at the bottom of the file, while `XRef` table would be just above the `trailerDict

short answer, use the following code `const pdfBytes = await pdfDoc.save({ useObjectStreams: false });` 

and you will get something similar to 
```
xref
0 9
0000000000 65535 f 
0000000016 00000 n 
0000000251 00000 n 
0000000454 00000 n 
0000000689 00000 n 
0000000892 00000 n 
0000001127 00000 n 
0000001330 00000 n 
0000001565 00000 n 
```

I've committed the sample version that can get the xRef to 

https://github.com/PhakornKiong/pdf-lib/tree/issue/trailerData

Just run `yarn scratchpad:run` and you should get the output pdf in the format that you wanted.
https://github.com/PhakornKiong/pdf-lib/blob/bc5ccf9ddf3f1fdfb5ab50ab3ecd914b3dff08cd/scratchpad/index.ts#L5-L25

Long answer, `pdf-lib` try to write object as `stream` since it is compressed.

**Comment by ealloradai** [comment]
Hi
thank you for you answer. I actually just neded to know, via pdf-lib, if a pdf file has the XRef as table or stream and the last XRef offset. I have obtained those informations subclassing the PDFParser and using essencially those lines of  code

`haveXRefTable = this.maybeParseCrossRefSection(); /* Find XRef Table */`

`this.maybeParseTrailerDict();`

`trailerOffset = this.maybeParseTrailer(); /* Find XRef Stream */`

`return [trailerOffset.lastXRefOffset, haveXRefTable ? true : false];`
