### ISSUE TITLE
Cannot increase size of PDF page

### ISSUE THREAD

**Issue by ahaw** [Hopding/pdf-lib#969]
I cannot incrase size using setSize method.
firstPage.setSize(width+200, height+100)
It works well when I'm shrinking image. 

What could be the reason?

Im using this example to test: https://jsfiddle.net/j5L38u1h/8/

**Comment by Hopding** [comment]
Looks like this is probably a bug. I'll dig into this further when I get a chance.

**Comment by bouyuc** [comment]
I was testing this bug using version v1.17.1 and it seems be have been fixed.

Below are the steps I took:
1. Copied the HTML and CSS files to my local machine
2. Cloned the pdf-lib repo
3. Build the pdf-lib using npm run build
4. Edited the HTML file to reference the local build 

I believe you can just update the jsfiddle to use https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js instead of  https://unpkg.com/pdf-lib@1.4.0
