### ISSUE TITLE
Firebase Cloud Functions

### ISSUE THREAD

**Issue by Leo1212** [Hopding/pdf-lib#98]
Hi 
I'm trying to edit a PDF file with a cloud function from Firebase.
While I don't get any problems running it locally, I get the error while deploying it to Firebase.
Can anybody help me?

These are my dependencyes:
```
"dependencies": {
    "@sentry/node": "^5.0.7",
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.1.0",
    "nodemailer": "^5.1.1",
    "pdf-lib": "^0.6.1"
  },
  "devDependencies": {
    "@types/node": "^11.9.4",
    "rimraf": "^2.6.3",
    "tslint": "^5.8.0",
    "typescript": "^2.5.3"
  },
```
I minimized the code to just one Line:

```
import { PDFDocumentFactory } from 'pdf-lib';

export const registerUser = functions.https.onRequest(async (req, res) => {
    try {
        
        let test = PDFDocumentFactory;
        ...
```

Just this line produces this exception.

```
!  functions[registerUser(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Object.values is not a function
    at Object.<anonymous> (/user_code/node_modules/pdf-lib/lib/core/pdf-document/index.js:15:30)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Function.<anonymous> (/user_code/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Function._load (/user_code/node_modules/@sentry/node/dist/integrations/http.js:64:47)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```

**Comment by Hopding** [comment]
Hello @Leo1212. What version of Node is your cloud function running? It looks like it might be an older version that doesn't support the [`Object.values()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) function. `pdf-lib` uses this function [here](https://github.com/Hopding/pdf-lib/blob/master/src/core/pdf-document/index.ts#L9).

I think you have two options:
* Update your Node version so it support `Object.values()`.
* Otherwise, you can try polyfilling it. See https://github.com/Hopding/pdf-lib/issues/74#issuecomment-466776423.

**Comment by Leo1212** [comment]
Wow. Thanks.
Adding `
"engines": { 
    "node": "8" 
  }
` to the `/functions/package.json` solved the problem.

Thanks @Hopding !
